#!/usr/bin/env node
// scripts/audit/classify-modules.mjs — classifies every production module
// as shared/cloud/local/composition-full/composition-lite/mixed, and
// computes real reachability from BOTH composition roots, using the
// AST-derived import graph from build-import-graph.mjs — not assertion,
// not file-path guessing, not a hand-maintained root-imports list.
//
// Read-only: reads docs/design/artifacts/full-lite-import-graph.json
// (regenerated by build-import-graph.mjs, itself now covering BOTH src/
// and packages/lite/lite-src/ as real parsed AST nodes in one unified
// REPO_ROOT-relative graph — see that file's own header comment for why
// this replaced an earlier hand-maintained LITE_SRC_ENTRY_IMPORTS
// constant, which code review correctly flagged as a silent-drift risk:
// a new import added to a Lite entry point with no matching update to a
// hand-copied list would have left every downstream check green while
// actually missing the new edge). Writes
// docs/design/artifacts/full-lite-module-inventory.json. Never modifies
// src/, packages/lite/, or any other production file.
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGraph } from './build-import-graph.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..');
const ARTIFACTS_DIR = join(REPO_ROOT, 'docs', 'design', 'artifacts');

// ── Composition roots ────────────────────────────────────────────────────
//
// Every path in this file is now REPO_ROOT-relative (e.g.
// "src/core/config.js", "packages/lite/lite-src/doctor-lite.js"),
// matching build-import-graph.mjs's own node-key convention.
//
// "Full" reachability starts from every real Full entry point a user or
// script actually launches: the admin server, the indexer CLI, the MCP
// server, the Full Admin UI's own browser bundle entry, plus the
// maintenance/dev CLIs (sync, doctor, backfill*, smoke, bootstrap-docs) —
// all of these are genuine Full-only entry points with no Lite equivalent,
// confirmed against package.json's own "scripts" and packages/lite/build.mjs's
// EXCLUDE_FILES list.
//
// Phase 8A finding: src/admin/ui-src/entries/full.js (the real Vite JS
// entry the Full Admin UI's <script type="module"> tag loads — see
// src/admin/ui-src/index.html) was previously NOT a traced root here at
// all — the whole admin/ui-src/ browser bundle was only ever classified by
// a hand-verified directory-pattern special case in firstPassBucket()
// below, never by real reachability, because nothing in the SERVER-side
// graph statically imports a browser entry point (Vite bundles it
// separately). Adding it as a real root closes that gap: the UI's own
// import graph (app.js, router.js, global-settings-view.js, etc., plus the
// one real cross-boundary edge into
// cloud/embedding/qdrant-cloud-models.js, a pure-data zero-dependency
// module — confirmed by reading its own header comment) is now traced the
// same way every other entry point is, not hand-verified prose.
export const FULL_ROOTS = [
  'src/admin/bootstrap.js',
  'src/indexer/index.js',
  'src/indexer/index-full.js',
  'src/mcp/server.js',
  'src/sync.js',
  'src/doctor.js',
  'src/backfill-tags.js',
  'src/backfill-entity-refs.js',
  'src/smoke.js',
  'src/bootstrap-docs.js',
  'src/admin/ui-src/entries/full.js',
  // scripts/*.ps1 -> `node <js-path>` invocations, computed below by
  // findPowerShellInvokedRoots() and spread in — a real cross-language
  // process boundary (PowerShell spawning node as its own child process)
  // that build-import-graph.mjs's AST parser cannot see and never will,
  // since it only parses .js/.mjs files. Not a hand-maintained list: any
  // `.ps1` under scripts/ that invokes a src/ file via `node <path>` is
  // picked up automatically, so a file genuinely reachable only from a
  // PowerShell installer/maintenance script is never misclassified as
  // dead code by shared-cloud-local-manifest.test.js's zero-unclassified
  // guard. See findPowerShellInvokedRoots()'s own header for the exact
  // pattern it matches.
  ...findPowerShellInvokedRoots(),
];

// Scans every scripts/**/*.ps1 file's own text for `node <relative-path>`
// invocations (the exact shape src/local/core/*.js's own CLI-entry files
// document as their invocation contract — see e.g.
// onnx-cuda-prereq-check.js's header comment) and resolves each matched
// path to a REPO_ROOT-relative src/ file path. Deliberately simple/
// conservative: matches `node <path-ending-in-.js>` where <path> is a
// bare relative path (no shell variables, no quoting) — exactly the
// literal shape every real .ps1 caller in this repo uses today (verified
// by reading install-onnxruntime-cuda-windows.ps1's own $scriptPath /
// $verifyScript invocation lines). A more elaborate path expression
// (variable interpolation, string concatenation) would silently fail to
// match here — this is intentionally NOT a full PowerShell parser, only
// a targeted scan for the one pattern this codebase's own CLI-entry files
// are documented to expect. If a future .ps1 script invokes a src/ file
// through a shape this regex can't see, that file's reachability must be
// re-established some other way (e.g. a doctor.js call, as
// onnx-cuda-prereq-check.js's own header comment discusses) — this
// function does not silently paper over that gap, it simply won't find
// an edge that isn't there in the exact literal shape it looks for.
function findPowerShellInvokedRoots() {
  const scriptsDir = join(REPO_ROOT, 'scripts');
  if (!existsSync(scriptsDir)) return [];
  const roots = new Set();
  const NODE_INVOCATION_RE = /\bnode\s+(?:\$\w+\s*=\s*)?(?:["'`]?)([\w./\\-]+\.js)(?:["'`]?)/g;
  const walk = (dir) => {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
      const full = join(dir, entry.name);
      if (entry.isDirectory()) { walk(full); continue; }
      // .psm1 too — Invoke-NodeDecision/Invoke-VerifierSafely (the actual
      // `node <path>` call sites) were pulled out of
      // install-onnxruntime-cuda-windows.ps1 into a sibling .psm1 module
      // (Invoke-VerifierSafely's own P1 fix — pulling the helper into its
      // own importable module is what let a real PowerShell test exercise
      // it directly, see tests/powershell/install-onnxruntime-cuda-windows.tests.ps1),
      // so the .ps1 file alone no longer contains every real invocation
      // this scan needs to find.
      if (!entry.name.endsWith('.ps1') && !entry.name.endsWith('.psm1')) continue;
      const text = readFileSync(full, 'utf-8');
      for (const line of text.split('\n')) {
        // Only lines that actually invoke `node` as a command (not merely
        // mentioning the word) AND reference a path under src/ — a
        // $scriptPath variable assigned from Join-Path is resolved
        // one line prior in every real caller in this repo, so this scans
        // for the literal `node $scriptPath`-style call by instead
        // matching direct relative-path invocations AND the two-line
        // $var = Join-Path ...; node $var pattern via a second pass below.
        const directMatch = [...line.matchAll(NODE_INVOCATION_RE)];
        for (const m of directMatch) {
          const rel = m[1].replace(/\\/g, '/');
          if (rel.startsWith('src/')) roots.add(rel);
        }
      }
      // Second pass: `$scriptPath = Join-Path $RepoRoot 'src\...\x.js'` ...
      // `node $scriptPath` — resolves the variable's own MOST RECENTLY
      // assigned path literal at the point of use (matching PowerShell's
      // actual reassignment semantics — the same variable name, e.g.
      // $scriptPath, is legitimately reused for different paths across
      // different helper functions in the same file, so a whole-file
      // name->path map would silently let a later assignment overwrite an
      // earlier one before its own `node $var` call is ever matched
      // against it). Walked line-by-line, tracking the live value of each
      // variable as the scan proceeds top-to-bottom.
      const varAssignRe = /^\s*\$(\w+)\s*=\s*Join-Path\s+\$\w+\s+['"]([^'"]+\.js)['"]/;
      // Matches BOTH a direct `node $var` call AND an indirect one through
      // a wrapper function's own -<Param> $var argument (e.g.
      // `Invoke-VerifierSafely -RuntimeDir $TargetDir -VerifyScript
      // $verifyScript`, defined in install-onnxruntime-cuda-windows.lib.psm1,
      // which itself calls `& $NodeCommand $VerifyScript` — a shape this
      // regex-based scan cannot trace through a second file/function
      // boundary). Any named parameter whose own name ends in
      // Script/Path is treated as carrying a script path through to a
      // real `node` invocation somewhere inside the function it's passed
      // to — deliberately broad (would also match a hypothetical
      // -ConfigPath $var that has nothing to do with node), but this is
      // scripts/ only, a small, human-reviewed directory, not arbitrary
      // user input, so a rare false-positive root is a acceptable
      // trade-off for not silently missing a real one.
      const nodeVarCallRe = /\bnode\s+\$(\w+)\b|-(?:\w*(?:Script|Path))\s+\$(\w+)\b/;
      const liveVarToPath = new Map();
      for (const line of text.split('\n')) {
        const assign = line.match(varAssignRe);
        if (assign) {
          liveVarToPath.set(assign[1], assign[2].replace(/\\/g, '/'));
          continue;
        }
        const call = line.match(nodeVarCallRe);
        const varName = call ? (call[1] ?? call[2]) : null;
        if (varName && liveVarToPath.has(varName)) {
          roots.add(liveVarToPath.get(varName));
        }
      }
    }
  };
  walk(scriptsDir);
  return [...roots];
}

// "Lite" reachability starts from packages/lite/lite-src/*.js — now REAL
// parsed graph nodes (build-import-graph.mjs walks that directory too),
// so this is simply "every file under that directory," not a
// hand-transcribed import list. index-lite.js does NOT statically import
// indexer/run.js — it spawns indexer/index.js as a CHILD PROCESS via
// admin/jobs/registry.js's createJobRegistry().startIndexJob()
// (spawn(process.execPath, [INDEXER_ENTRY, path], ...)). indexer/index.js
// (and everything it transitively imports, including indexer/run.js)
// therefore only enters Lite's reachable set via registry.js's own
// fork/spawn edge in the graph — NOT via a synthetic root. This was the
// single most consequential finding while first hand-verifying this
// boundary: the FIRST version of build-import-graph.mjs's spawn-target
// extraction (ported from packages/lite/build.mjs) silently failed to
// resolve this exact edge (spawn aliased to nodeSpawn, then flowed
// through a default-parameter named spawnFn, called as
// spawn(process.execPath, [ENTRY, ...], opts) — a shape neither the
// original build.mjs NOR the first draft of this repo's extractor
// actually recognized, despite build.mjs's own header comment claiming
// to). Fixed in build-import-graph.mjs (AssignmentPattern default-param
// tracking + process.execPath-aware spawn-arg resolution) — see the
// design doc's Part C/Part K findings for the full writeup.
export const LITE_SRC_DIR = 'packages/lite/lite-src/';

// Phase 8A finding: the mirror-image gap to FULL_ROOTS's own fix above —
// src/admin/ui-src/entries/lite.js (the real Vite JS entry
// src/admin/ui-src/lite-entry/index.html's <script type="module"> tag
// loads) was not a traced reachability root either, for the same reason.
// Added to the Lite reachability computation in main() below (NOT
// unioned into liteSyntheticRoots itself, which also drives the separate
// "give every packages/lite/lite-src/*.js file its own composition-lite
// inventory entry" loop later in this file — entries/lite.js gets its own
// inventory entry from the main per-file loop instead, correctly
// classified 'composition' via firstPassBucket(), not a second synthetic
// entry).
export const LITE_UI_ENTRY = 'src/admin/ui-src/entries/lite.js';

function loadOrBuildGraph() {
  // Always rebuilt fresh, never trusted stale — a stale cached JSON from
  // before a src/ change would silently make every reachability/
  // classification computation below wrong in a way this script itself
  // could not detect. buildGraph() is a fast, pure, read-only AST parse
  // (sub-second over 236 files), so there is no real cost to always
  // recomputing it rather than trusting a possibly-stale artifact on disk.
  return buildGraph();
}

// LAZY_SHIM_SUBSTITUTIONS is now permanently EMPTY (code review, round 4 —
// the *-lazy.js content-substitution mechanism was removed from
// packages/lite/build.mjs entirely). Before this, core/ollama-lazy.js/
// core/onnx-embed-lazy.js/indexer/phases/tag-onnx-lazy.js were each staged
// with their *.lite.js shim's CONTENT substituted at build time, because
// several files (core/embeddings.js, indexer/run.js, the phase modules,
// core/generation/ollama-provider.js) statically imported the REAL module
// at their own module scope as a default value. All of those were migrated
// to explicit capability injection with no real-module default of their
// own (null until a composition root calls applyXCapability()), and
// indexer/index.js was split into index-full.js (Full-only, excluded from
// the Lite package) and index-lite.js (imports none of the three) — so
// nothing in the Lite-staged closure imports any of the three real
// *-lazy.js modules anymore, and the shim-substitution mechanism that used
// to paper over that has nothing left to do. Kept as an empty object (not
// deleted outright) so applyLiteShims below stays a well-defined, always-
// safe no-op rather than requiring every call site across this codebase
// (and its own test suite) to drop the option in lockstep.
export const LAZY_SHIM_SUBSTITUTIONS = {};

// Real, resolved-edge-only reachability (relative imports/dynamic imports/
// requires/fork-spawn targets that resolved to an actual staged file) —
// bare package specifiers and unresolved specifiers are NOT graph nodes,
// they're recorded separately per-file as "external deps"/"unresolved".
//
// applyLiteShims: now always a no-op (LAZY_SHIM_SUBSTITUTIONS is empty —
// see that constant's own comment) — accepted for backward compatibility
// with existing call sites, but pre-shim and post-shim reachability are
// now IDENTICAL by construction, since there is nothing left to
// substitute.
export function computeReachable(graph, roots, { applyLiteShims = false } = {}) {
  const reachable = new Set();
  const queue = [...roots];
  while (queue.length) {
    const file = queue.pop();
    if (reachable.has(file)) continue;
    const shimTarget = applyLiteShims ? LAZY_SHIM_SUBSTITUTIONS[file] : null;
    const node = shimTarget ? graph.nodes[shimTarget] : graph.nodes[file];
    if (!node) continue; // root not in graph (shouldn't happen for real roots) or unresolved edge
    reachable.add(file);
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) queue.push(ref.resolved);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.literal && fs.resolved) queue.push(fs.resolved);
    }
  }
  return reachable;
}

// Every bare-package specifier reachable from a given reachable-file set —
// used to answer "does this reachable subgraph actually import a heavy
// native package" without conflating it with a file that merely MENTIONS
// the package name in a comment.
export function collectExternalDeps(graph, reachableSet) {
  const deps = new Map(); // pkgName -> Set(files that import it)
  for (const file of reachableSet) {
    const node = graph.nodes[file];
    if (!node) continue;
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'package') {
          if (!deps.has(ref.resolved)) deps.set(ref.resolved, new Set());
          deps.get(ref.resolved).add(file);
        }
      }
    }
  }
  return deps;
}

export const HEAVY_LOCAL_PACKAGES = ['onnxruntime-node', '@huggingface/transformers'];

// Directory/file-based FIRST-PASS classification signal — deliberately
// coarse (directory alone is not proof; see the "grounded by graph" pass
// below, which can override this using real reachability facts). This
// mirrors packages/lite/build.mjs's own EXCLUDE_FILES/EXCLUDE_DIRS list —
// re-derived independently here (not imported from build.mjs) so this
// audit script has no dependency on the packaging tool's internals and
// double-checks it rather than trusting it blindly.
export const LOCAL_ONLY_PATH_PATTERNS = [
  /^src\/local\/core\/onnx-embed\.js$/, /^src\/local\/core\/onnx-runtime\.js$/, /^src\/local\/core\/onnx-probe-runner\.js$/,
  /^src\/local\/core\/onnx-provider-probe\.js$/, /^src\/local\/core\/length-bucket\.js$/, /^src\/core\/ce-rerank\.js$/,
  /^src\/core\/ce-rerank-worker\.js$/, /^src\/local\/core\/ollama\.js$/, /^src\/local\/core\/ollama-models\.js$/,
  /^src\/local\/indexer\/phases\/tag-onnx\.js$/, /^src\/local\/indexer\/workers\/tag-onnx-worker\.js$/,
  /^src\/admin\/system\/ollama\.js$/, /^src\/admin\/api\/onnx\.js$/, /^src\/admin\/api\/ollama-models\.js$/,
  // Reproducible Windows CUDA onnxruntime-node managed installer — every
  // new src/local/core/ file this task added, mirroring build.mjs's own
  // wholesale 'local' EXCLUDE_DIRS entry (see this const's own header
  // comment: this list is a file-by-file double-check of that directory
  // exclusion, not a separate policy).
  //
  // onnx-cuda-prereq-check.js, onnx-cuda-installer-logic.js, and
  // onnx-cuda-installer-verify.js are each invoked by
  // scripts/install-onnxruntime-cuda-windows.ps1 as `node <path>` — a real
  // cross-language process boundary this JS-only import-graph parser
  // cannot see as a static/dynamic import edge. FULL_ROOTS above spreads
  // in findPowerShellInvokedRoots()'s own automated scan of every
  // scripts/**/*.ps1 file for exactly this invocation shape, so these
  // files are genuinely graph-provable Full-reachable roots, not
  // hand-asserted exceptions — see that function's own header comment for
  // the exact pattern it matches. onnx-cuda-prereq-check.js is ALSO
  // called directly from src/doctor.js (see its "GPU-stack prerequisites
  // (informational)" report line), independent of the .ps1 scan.
  /^src\/local\/core\/semidex-home\.js$/, /^src\/local\/core\/managed-runtime-id\.js$/,
  /^src\/local\/core\/managed-onnx-runtime-manifest\.js$/, /^src\/local\/core\/onnx-cuda-prereq-check\.js$/,
  /^src\/local\/core\/onnx-runtime-source-resolution\.js$/, /^src\/local\/core\/onnx-cuda-installer-logic\.js$/,
  /^src\/local\/core\/onnx-cuda-installer-verify\.js$/,
];
export const COMPOSITION_FULL_PATTERNS = [
  /^src\/admin\/bootstrap\.js$/, /^src\/admin\/server-full\.js$/, /^src\/doctor\.js$/, /^src\/backfill-tags\.js$/,
  /^src\/backfill-entity-refs\.js$/, /^src\/sync\.js$/, /^src\/smoke\.js$/, /^src\/bootstrap-docs\.js$/,
];
// Phase 8B Step 6 — physically relocated from src/core/embedding-profile/
// (qdrant-cloud-{catalog,tokenizer}.js — qdrant-cloud-models.js itself moved
// BACK to src/core/embedding-profile/, see the code review fix below),
// src/core/gemini-models.js, src/core/generation/gemini-provider.js,
// src/admin/api/qdrant-cloud.js, and src/admin/system/qdrant-cloud.js to
// src/cloud/{embedding,generation,admin}/.
//
// Code review fix (Phase 8B Step 6, second pass): qdrant-cloud-models.js is
// genuinely neutral catalog/typed-metadata data (zero dependencies, no fs,
// no fetch, no tokenizer) and was moved back to src/core/embedding-profile/
// — a real architectural boundary requires distinguishing pure data from
// implementation, not just where a file happens to sit. cloud-embedding-
// provider.js/cloud-generation-provider.js are the two narrow composition-
// facing factories (createCloudEmbeddingCapability()/
// createCloudGenerationCapability()) that a composition root imports to
// obtain the real capability — they physically live in src/cloud/ and are
// never imported by shared code, so they belong in this pattern list too.
export const CLOUD_ONLY_PATH_PATTERNS = [
  /^src\/cloud\/embedding\/qdrant-cloud/, /^src\/cloud\/admin\/qdrant-cloud-system\.js$/,
  /^src\/cloud\/admin\/qdrant-cloud-api\.js$/, /^src\/cloud\/generation\/gemini-models\.js$/,
  /^src\/cloud\/generation\/gemini-provider\.js$/, /^src\/cloud\/embedding\/cloud-embedding-provider\.js$/,
  /^src\/cloud\/generation\/cloud-generation-provider\.js$/,
];
const LAZY_SHIM_PATTERNS = [/-lazy\.js$/, /-lazy\.lite\.js$/];

// packages/lite/build.mjs's REAL, COMPLETE EXCLUDE_DIRS and EXCLUDE_FILES —
// extracted verbatim from that file's own source, not a partial
// re-derivation. Code review correctly flagged that an earlier version of
// this script's liteTarballStaged computation only checked
// LOCAL_ONLY_PATH_PATTERNS plus the directory list, silently missing several
// of build.mjs's real exclusions (admin/bootstrap.js, admin/server-full.js,
// doctor.js, backfill-tags.js, backfill-entity-refs.js, sync.js, smoke.js,
// bootstrap-docs.js — every one of COMPOSITION_FULL_PATTERNS above, none of
// which is local-runtime-coupled, all of which are still genuinely EXCLUDED
// from the Lite tarball) — so those files were wrongly reported
// liteTarballStaged: true. Fixed by unioning BOTH pattern lists into the
// exclusion check, matching build.mjs's real EXCLUDE_FILES list file-for-
// file. Phase 8B Step 2 added 'src/local/' here to mirror build.mjs's own
// EXCLUDE_DIRS addition, once the ONNX runtime files physically moved under
// that directory — LOCAL_ONLY_PATH_PATTERNS above is kept in sync too
// (independent re-derivation, not a shared import, by design — see this
// comment's own opening line).
const EXCLUDE_DIRS = ['src/admin/ui-src/', 'src/mcp/', 'src/smoke/', 'src/test-fixtures/', 'src/local/'];
const ALL_EXCLUDED_FILE_PATTERNS = [...LOCAL_ONLY_PATH_PATTERNS, ...COMPOSITION_FULL_PATTERNS];

// admin/ui-src/entries/{full,lite}.js are the real Vite JS entry points
// (Phase 8A finding — see FULL_ROOTS's/LITE_UI_ENTRY's own comments for
// why they were not traced roots before this). Each is a genuine
// composition root for its own browser bundle, exactly analogous to
// admin/server-full.js / admin/composition/lite.js on the server side —
// classified explicitly here rather than left to the generic reachability
// fallback (which would otherwise call entries/full.js 'local' — Full-
// reachable, never Lite-reachable — a misleading label for a composition
// root that itself contains no local-runtime logic of its own, only
// wiring).
const UI_COMPOSITION_FULL_PATTERNS = [/^src\/admin\/ui-src\/entries\/full\.js$/];
const UI_COMPOSITION_LITE_PATTERNS = [/^src\/admin\/ui-src\/entries\/lite\.js$/];

function firstPassBucket(file) {
  if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(file))) return 'local';
  if (COMPOSITION_FULL_PATTERNS.some((p) => p.test(file)) || UI_COMPOSITION_FULL_PATTERNS.some((p) => p.test(file))) return 'composition-full';
  if (UI_COMPOSITION_LITE_PATTERNS.some((p) => p.test(file))) return 'composition-lite';
  if (CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(file))) return 'cloud';
  if (LAZY_SHIM_PATTERNS.some((p) => p.test(file))) return 'mixed'; // lazy wrappers are a real boundary seam, always reviewed by hand
  // Phase 4 (docs/design/full-lite-shared-architecture-audit-2026-08-01.md):
  // createLiteApp() moved out of server.js into composition/lite.js.
  // server.js now hosts only resolveHostConfig/resolvePortConfig (shared
  // bind-config utility) — reachable from both Full and Lite, genuinely
  // 'shared', no longer 'mixed'. composition/lite.js is Lite's own real
  // composition root now — reachable only from Lite's roots, so the
  // graph-facts pass below correctly classifies it 'cloud' with no special
  // case needed here (it has no Full-reachable edge to conflict with).
  //
  // Phase 8A: admin/ui-src/*.js used to be treated as OUTSIDE this script's
  // traced graph entirely (a stale premise — see FULL_ROOTS's own comment
  // on why entries/full.js/entries/lite.js are now real roots), which is
  // why global-settings-view.js/settings-view.js were previously HARD-CODED
  // 'mixed' here based on a hand-grep, not graph facts. That hardcoding is
  // now removed: with entries/full.js and entries/lite.js as real roots,
  // the graph-facts pass below correctly finds both files
  // fullReachable && liteReachable (genuinely 'shared' — Phase 6's
  // capability-injection seam moved every ONNX/Ollama-specific line out
  // into local-features.js, which the graph now correctly reports as
  // fullReachable && !liteReachable, i.e. 'local', on its own, no special
  // case needed for IT either). No remaining admin/ui-src/*.js file needs
  // a directory-wide fallback rule any more — every one of them is now a
  // real graph node reachable from a real root, so `return null` below
  // (falling through to the graph-facts pass) is correct for all of them.
  return null; // undetermined by pattern — graph facts decide
}

// Code review finding: a Full-only classification ("reachable from Full,
// never from Lite") was previously conflated with "local-runtime-coupled"
// under one 'local' bucket — misleading, since most of mcp/'s 14 files
// (11 of them, see below) are reachable ONLY from Full purely because
// Lite has no MCP entry point at all today, NOT because they import
// anything ONNX/Ollama-specific. Two independent axes, reported
// separately: `runtimeCoupling` ('local'|'cloud'|'none') answers "does
// this file's OWN direct-dependency set include a real ONNX/Ollama/heavy-
// native edge," computed from the graph, not from directory location.
// `classification` keeps its existing shared/local/cloud/mixed/etc.
// vocabulary for the top-level bucket (still useful, still what most
// consumers of this inventory want first), but a `local` classification
// caused purely by missing Lite entry-point coverage (Full-reachable,
// zero local-runtime edges of its own) is now distinguishable via
// runtimeCoupling: 'none' — see main()'s classification logic below,
// which checks the file's OWN local-only dependency edges (not just
// Full-vs-Lite reachability) before finalizing 'local'.
function computeRuntimeCoupling(graph, file) {
  const node = graph.nodes[file];
  if (!node) return 'none';
  const relDeps = [];
  for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
    for (const ref of group) {
      if (ref.kind === 'relative' && ref.resolved) relDeps.push(ref.resolved);
    }
  }
  for (const fs of node.forkSpawnCalls) {
    if (fs.resolved) relDeps.push(fs.resolved);
  }
  const ownDepsAreLocal = relDeps.some((d) => LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(d)));
  const ownDepsAreCloud = relDeps.some((d) => CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(d)));
  if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(file)) || ownDepsAreLocal) return 'local';
  if (CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(file)) || ownDepsAreCloud) return 'cloud';
  return 'none';
}

// Deterministic recommendedAction, computed from facts already gathered —
// never a hand-filled placeholder (code review finding: every one of the
// 236 prior entries had recommendedAction: null despite the artifact
// being presented as a complete per-module inventory). Four possible
// values, matching the JSON schema documented in the design doc's Part L:
// 'keep' (no action needed), 'split' (genuinely mixed, needs a real code
// split — see the design doc's §4 for the human-reviewed detail behind
// each), 'move' (correctly placed today but a candidate for physical
// relocation once a real shared/cloud/local directory structure exists —
// Phase 8 territory, not urgent), 'exclude' (should never be reachable
// from Lite and today correctly isn't).
function computeRecommendedAction(file, { classification, runtimeCoupling, liteReachable, liteTarballStaged }) {
  if (classification === 'mixed') return 'split';
  if (classification === 'composition-full' || classification === 'composition-lite') return 'keep';
  if (classification === 'local') {
    // Distinguishes the P2 finding precisely: a file that is Full-only
    // AND has zero local-runtime coupling of its own (most of mcp/'s 11
    // provider-neutral tool files) is a 'move' candidate (it could become
    // 'shared' once Lite gains an entry point that reaches it — no code
    // change needed in the file itself); a file with REAL local-runtime
    // coupling (onnxruntime-node/Ollama edges) is correctly 'exclude'.
    if (runtimeCoupling === 'none') return 'move';
    return liteReachable ? 'split' : 'exclude'; // liteReachable+local should never co-occur post-shim; 'split' flags it for review if it ever does
  }
  if (classification === 'cloud' || classification === 'shared') return 'keep';
  if (classification === 'unclear') return 'keep'; // e.g. the two test-only contract validators — see design doc §6.9
  return 'keep';
}

function main() {
  const graph = loadOrBuildGraph();

  const fullReachable = computeReachable(graph, FULL_ROOTS);
  // Union of every real file under packages/lite/lite-src/ (now genuine
  // graph nodes, not a hand-transcribed import list — see this file's own
  // header comment). Computed TWICE: liteReachablePreShim reflects real
  // src/ as it exists in the repo (what a naive "just stage everything
  // reachable" tool would see); liteReachable (post-shim) additionally
  // applies build.mjs's own *-lazy.js -> *-lazy.lite.js content
  // substitution, matching what ACTUALLY ships in the tarball. The gap
  // between the two sets is exactly the set of files the lazy-shim
  // mechanism is responsible for cutting — reported explicitly below, not
  // silently discarded.
  const liteSyntheticRoots = graph.files.filter((f) => f.startsWith(LITE_SRC_DIR));
  const liteReachabilityRoots = [...liteSyntheticRoots, LITE_UI_ENTRY];
  const liteReachablePreShim = computeReachable(graph, liteReachabilityRoots, { applyLiteShims: false });
  const liteReachable = computeReachable(graph, liteReachabilityRoots, { applyLiteShims: true });
  const shimCutFiles = [...liteReachablePreShim].filter((f) => !liteReachable.has(f)).sort();

  const fullExternalDeps = collectExternalDeps(graph, fullReachable);
  const liteExternalDeps = collectExternalDeps(graph, liteReachable);
  const liteExternalDepsPreShim = collectExternalDeps(graph, liteReachablePreShim);

  const liteHeavyDepsReachable = HEAVY_LOCAL_PACKAGES.filter((p) => liteExternalDeps.has(p));
  const fullHeavyDepsReachable = HEAVY_LOCAL_PACKAGES.filter((p) => fullExternalDeps.has(p));

  // Code review P2 finding: "cloud never imports local" was asserted in
  // the design doc's Part K list but never actually checked anywhere —
  // only Lite-reachability-excludes-local was checked. Real check: for
  // every CLOUD_ONLY_PATH_PATTERNS file, walk its OWN direct dependency
  // edges (not transitively — a direct violation is the meaningful unit
  // here, matching how the other direction-rules in this script work) and
  // flag any that resolve to a LOCAL_ONLY_PATH_PATTERNS file.
  const cloudFiles = graph.files.filter((f) => CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(f)));
  const cloudImportsLocalViolations = [];
  for (const file of cloudFiles) {
    const node = graph.nodes[file];
    const relDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) relDeps.push(ref.resolved);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.resolved) relDeps.push(fs.resolved);
    }
    for (const dep of relDeps) {
      if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(dep))) {
        cloudImportsLocalViolations.push({ from: file, to: dep });
      }
    }
  }

  const inventory = [];
  for (const file of graph.files) {
    if (file.startsWith(LITE_SRC_DIR)) continue; // handled in the composition-lite pass below, with entryPoints: ['lite'] instead of reachability-derived
    const node = graph.nodes[file];
    const inFull = fullReachable.has(file);
    const inLite = liteReachable.has(file);

    const directDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) directDeps.push(ref.resolved);
        else if (ref.kind === 'package') directDeps.push(`pkg:${ref.resolved}`);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.resolved) directDeps.push(fs.resolved);
    }

    let classification = firstPassBucket(file);
    if (!classification) {
      if (inFull && inLite) classification = 'shared';
      else if (inFull && !inLite) classification = 'local'; // reachable ONLY from Full's own graph traversal, never Lite's — see runtimeCoupling below for whether this is REALLY local-runtime-coupled or just missing Lite entry-point coverage (§6.6 of the design doc)
      else if (!inFull && inLite) classification = 'cloud'; // reachable only via Lite's synthetic roots (shouldn't normally happen since Full imports Lite's whole cloud surface too, but recorded honestly if found)
      else classification = 'unclear'; // reachable from neither traced root set — dead code, test-only helper, or genuinely orphaned
    }

    const runtimeCoupling = computeRuntimeCoupling(graph, file);

    // Two DISTINCT questions, deliberately not conflated (Part C's own
    // required distinction): "does build.mjs's STAGING step copy this
    // specific file's bytes into packages/lite/src/" (liteTarballStaged —
    // a pure exclude-list membership question, re-derived from
    // build.mjs's real, COMPLETE EXCLUDE_DIRS/EXCLUDE_FILES — 4 dirs, 18
    // files, verbatim, not a partial subset) vs. "is this file genuinely
    // REACHABLE from a real Lite entry point, post-lazy-shim-substitution"
    // (liteReachable, computed above — the thing that actually matters
    // for "can this code ever execute in Lite"). A file can be staged but
    // unreachable (dead weight in the tarball, not a safety problem) or —
    // the case that would actually matter — reachable without being
    // staged (impossible by construction here, since reachability is
    // computed FROM the same real src/ tree the staging list excludes
    // from, but the two are still reported as separate fields so this
    // invariant itself stays checkable rather than assumed).
    const inTarballDir = !EXCLUDE_DIRS.some((d) => file.startsWith(d));
    const inTarballFile = !ALL_EXCLUDED_FILE_PATTERNS.some((p) => p.test(file));
    // The three *.lite.js shim SOURCE files (core/ollama-lazy.lite.js,
    // core/onnx-embed-lazy.lite.js, indexer/phases/tag-onnx-lazy.lite.js)
    // are a real, cross-checked-against-the-actual-staged-tree exception:
    // build.mjs's substituteLazyShims() copies each one's CONTENT onto the
    // real module's path (e.g. core/ollama-lazy.js), then deletes the
    // separately-staged shim file under its own name — so the shim file
    // itself never survives staging under its own path, even though the
    // *.js file it targets (without .lite in the name) genuinely does.
    const isLazyShimSourceFile = /-lazy\.lite\.js$/.test(file);
    const liteTarballStaged = (inTarballDir && inTarballFile) && !isLazyShimSourceFile;

    const liteBrowserBundle = file.startsWith('src/admin/ui-src/');

    inventory.push({
      path: file,
      classification,
      runtimeCoupling,
      entryPoints: FULL_ROOTS.includes(file) ? ['full'] : [],
      directDependencies: [...new Set(directDeps)],
      fullReachable: inFull,
      liteReachable: inLite,
      liteReachablePreShim: liteReachablePreShim.has(file),
      liteTarballStaged,
      liteBrowserBundle,
      recommendedAction: computeRecommendedAction(file, { classification, runtimeCoupling, liteReachable: inLite, liteTarballStaged }),
    });
  }

  // packages/lite/lite-src/*.js — now real graph nodes (parsed by
  // build-import-graph.mjs alongside src/), appended here as explicit
  // composition-lite entries with their own real (not hand-transcribed)
  // directDependencies pulled straight from the graph.
  for (const liteSrcFile of liteSyntheticRoots) {
    const node = graph.nodes[liteSrcFile];
    const directDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) directDeps.push(ref.resolved);
        else if (ref.kind === 'package') directDeps.push(`pkg:${ref.resolved}`);
      }
    }
    inventory.push({
      path: liteSrcFile,
      classification: 'composition-lite',
      runtimeCoupling: 'none',
      entryPoints: ['lite'],
      directDependencies: [...new Set(directDeps)],
      fullReachable: false,
      liteReachable: true,
      liteReachablePreShim: true,
      liteTarballStaged: true, // packages/lite/package.json's "files" includes lite-src/ unconditionally
      liteBrowserBundle: false,
      recommendedAction: 'keep',
    });
  }

  mkdirSync(ARTIFACTS_DIR, { recursive: true });
  writeFileSync(join(ARTIFACTS_DIR, 'full-lite-module-inventory.json'), JSON.stringify(inventory, null, 2), 'utf-8');

  const counts = inventory.reduce((acc, m) => { acc[m.classification] = (acc[m.classification] ?? 0) + 1; return acc; }, {});
  const runtimeCouplingCounts = inventory.reduce((acc, m) => { acc[m.runtimeCoupling] = (acc[m.runtimeCoupling] ?? 0) + 1; return acc; }, {});
  // The precise number code review's P2 finding asked for: of the files
  // classified 'local', how many are ACTUALLY local-runtime-coupled vs.
  // merely Full-only-with-no-Lite-entry-point (e.g. 11 of mcp/'s 14
  // files).
  const localClassified = inventory.filter((m) => m.classification === 'local');
  const localGenuinelyCoupled = localClassified.filter((m) => m.runtimeCoupling === 'local').length;
  const localFullOnlyNoCoupling = localClassified.filter((m) => m.runtimeCoupling === 'none').length;

  const liteHeavyDepsReachablePreShim = HEAVY_LOCAL_PACKAGES.filter((p) => liteExternalDepsPreShim.has(p));

  console.log(`[audit] classified ${inventory.length} modules`);
  console.log('[audit] classification counts:', JSON.stringify(counts, null, 2));
  console.log('[audit] runtimeCoupling counts:', JSON.stringify(runtimeCouplingCounts, null, 2));
  console.log(`[audit] of ${localClassified.length} 'local'-classified modules: ${localGenuinelyCoupled} genuinely local-runtime-coupled, ${localFullOnlyNoCoupling} Full-only with NO local-runtime coupling of their own (mostly mcp/ — see design doc §6.6)`);
  console.log(`[audit] Full-reachable: ${fullReachable.size}`);
  console.log(`[audit] Lite-reachable PRE-shim (real src/, no build.mjs substitution): ${liteReachablePreShim.size}`);
  console.log(`[audit] Lite-reachable POST-shim (matches actual shipped tarball): ${liteReachable.size}`);
  console.log(`[audit] files the lazy-shim substitution removes from Lite's reachable set: ${shimCutFiles.length} -> ${JSON.stringify(shimCutFiles)}`);
  console.log(`[audit] heavy local packages reachable from LITE PRE-shim: ${JSON.stringify(liteHeavyDepsReachablePreShim)}`);
  console.log(`[audit] heavy local packages reachable from LITE POST-shim (actual tarball reality): ${JSON.stringify(liteHeavyDepsReachable)}`);
  console.log(`[audit] heavy local packages reachable from FULL roots: ${JSON.stringify(fullHeavyDepsReachable)}`);
  if (liteHeavyDepsReachablePreShim.length) {
    for (const dep of liteHeavyDepsReachablePreShim) {
      console.log(`  [pre-shim only] ${dep} reachable via: ${[...liteExternalDepsPreShim.get(dep)].join(', ')}`);
    }
  }
  if (liteHeavyDepsReachable.length) {
    for (const dep of liteHeavyDepsReachable) {
      console.log(`  [!! POST-SHIM — real problem] ${dep} reachable via: ${[...liteExternalDeps.get(dep)].join(', ')}`);
    }
  } else {
    console.log('  [ok] zero heavy local packages reachable POST-shim — matches the shipped tarball\'s actual dependency list.');
  }
  console.log(`[audit] cloud-imports-local violations: ${cloudImportsLocalViolations.length}${cloudImportsLocalViolations.length ? ' -> ' + JSON.stringify(cloudImportsLocalViolations) : ' (none — cloud correctly never imports local)'}`);

  writeFileSync(join(ARTIFACTS_DIR, 'full-lite-reachability-summary.json'), JSON.stringify({
    fullRoots: FULL_ROOTS,
    liteSyntheticRoots,
    lazyShimSubstitutions: LAZY_SHIM_SUBSTITUTIONS,
    fullReachableCount: fullReachable.size,
    liteReachablePreShimCount: liteReachablePreShim.size,
    liteReachableCount: liteReachable.size,
    shimCutFiles,
    fullReachableFiles: [...fullReachable].sort(),
    liteReachablePreShimFiles: [...liteReachablePreShim].sort(),
    liteReachableFiles: [...liteReachable].sort(),
    fullExternalDeps: Object.fromEntries([...fullExternalDeps.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteExternalDepsPreShim: Object.fromEntries([...liteExternalDepsPreShim.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteExternalDeps: Object.fromEntries([...liteExternalDeps.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteHeavyDepsReachablePreShim,
    liteHeavyDepsReachable,
    fullHeavyDepsReachable,
    cloudImportsLocalViolations,
    classificationCounts: counts,
    runtimeCouplingCounts,
    localGenuinelyCoupled,
    localFullOnlyNoCoupling,
  }, null, 2), 'utf-8');
  console.log(`[audit] wrote full-lite-reachability-summary.json and full-lite-module-inventory.json`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
