#!/usr/bin/env node
// scripts/audit/classify-modules.mjs — classifies every production module
// as shared/cloud/local/composition-full/composition-lite/mixed, and
// computes real reachability from BOTH composition roots, using the
// AST-derived import graph from build-import-graph.mjs — not assertion,
// not file-path guessing, not a hand-maintained root-imports list.
//
// Read-only: reads docs/design/artifacts/full-lite-import-graph.json
// (regenerated by build-import-graph.mjs, itself now covering BOTH src/
// and packages/lite/lite-src/ as real parsed AST nodes in one unified
// REPO_ROOT-relative graph — see that file's own header comment for why
// this replaced an earlier hand-maintained LITE_SRC_ENTRY_IMPORTS
// constant, which code review correctly flagged as a silent-drift risk:
// a new import added to a Lite entry point with no matching update to a
// hand-copied list would have left every downstream check green while
// actually missing the new edge). Writes
// docs/design/artifacts/full-lite-module-inventory.json. Never modifies
// src/, packages/lite/, or any other production file.
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildGraph } from './build-import-graph.mjs';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..', '..');
const ARTIFACTS_DIR = join(REPO_ROOT, 'docs', 'design', 'artifacts');

// ── Composition roots ────────────────────────────────────────────────────
//
// Every path in this file is now REPO_ROOT-relative (e.g.
// "src/core/config.js", "packages/lite/lite-src/doctor-lite.js"),
// matching build-import-graph.mjs's own node-key convention.
//
// "Full" reachability starts from every real Full entry point a user or
// script actually launches: the admin server, the indexer CLI, the MCP
// server, plus the maintenance/dev CLIs (sync, doctor, backfill*, smoke,
// bootstrap-docs) — all of these are genuine Full-only entry points with
// no Lite equivalent, confirmed against package.json's own "scripts" and
// packages/lite/build.mjs's EXCLUDE_FILES list.
export const FULL_ROOTS = [
  'src/admin/bootstrap.js',
  'src/indexer/index.js',
  'src/mcp/server.js',
  'src/sync.js',
  'src/doctor.js',
  'src/backfill-tags.js',
  'src/backfill-entity-refs.js',
  'src/smoke.js',
  'src/bootstrap-docs.js',
];

// "Lite" reachability starts from packages/lite/lite-src/*.js — now REAL
// parsed graph nodes (build-import-graph.mjs walks that directory too),
// so this is simply "every file under that directory," not a
// hand-transcribed import list. index-lite.js does NOT statically import
// indexer/run.js — it spawns indexer/index.js as a CHILD PROCESS via
// admin/jobs/registry.js's createJobRegistry().startIndexJob()
// (spawn(process.execPath, [INDEXER_ENTRY, path], ...)). indexer/index.js
// (and everything it transitively imports, including indexer/run.js)
// therefore only enters Lite's reachable set via registry.js's own
// fork/spawn edge in the graph — NOT via a synthetic root. This was the
// single most consequential finding while first hand-verifying this
// boundary: the FIRST version of build-import-graph.mjs's spawn-target
// extraction (ported from packages/lite/build.mjs) silently failed to
// resolve this exact edge (spawn aliased to nodeSpawn, then flowed
// through a default-parameter named spawnFn, called as
// spawn(process.execPath, [ENTRY, ...], opts) — a shape neither the
// original build.mjs NOR the first draft of this repo's extractor
// actually recognized, despite build.mjs's own header comment claiming
// to). Fixed in build-import-graph.mjs (AssignmentPattern default-param
// tracking + process.execPath-aware spawn-arg resolution) — see the
// design doc's Part C/Part K findings for the full writeup.
export const LITE_SRC_DIR = 'packages/lite/lite-src/';

function loadOrBuildGraph() {
  // Always rebuilt fresh, never trusted stale — a stale cached JSON from
  // before a src/ change would silently make every reachability/
  // classification computation below wrong in a way this script itself
  // could not detect. buildGraph() is a fast, pure, read-only AST parse
  // (sub-second over 236 files), so there is no real cost to always
  // recomputing it rather than trusting a possibly-stale artifact on disk.
  return buildGraph();
}

// packages/lite/build.mjs's own LAZY_SHIM_SUBSTITUTIONS list, re-derived
// here independently (not imported from build.mjs) for the same
// double-check-not-blind-trust reason the rest of this script avoids
// importing build.mjs's internals. When shimOverrides is provided,
// computeReachable() traverses a shimmed file's OWN (much smaller) real
// edge set instead of the real (repo) file's edges — this is what makes
// "Lite-reachable" mean "reachable in the ACTUAL shipped tarball," not
// merely "reachable in real repo src/ before Lite's build-time content
// substitution." Both numbers are legitimate and reported separately
// (see main()) — this is the exact "graph unreachability vs. physical
// absence" distinction the audit's Part C requires.
export const LAZY_SHIM_SUBSTITUTIONS = {
  'src/core/ollama-lazy.js': 'src/core/ollama-lazy.lite.js',
  'src/core/onnx-embed-lazy.js': 'src/core/onnx-embed-lazy.lite.js',
  'src/indexer/phases/tag-onnx-lazy.js': 'src/indexer/phases/tag-onnx-lazy.lite.js',
};

// Real, resolved-edge-only reachability (relative imports/dynamic imports/
// requires/fork-spawn targets that resolved to an actual staged file) —
// bare package specifiers and unresolved specifiers are NOT graph nodes,
// they're recorded separately per-file as "external deps"/"unresolved".
//
// applyLiteShims: when true, a file with a LAZY_SHIM_SUBSTITUTIONS entry
// is traversed using the SHIM file's own edges (queued under the REAL
// file's name, so the rest of the graph's edges pointing at the real name
// still resolve) rather than the real file's edges — modeling
// build.mjs's content substitution rather than the graph's raw, pre-
// substitution reality.
export function computeReachable(graph, roots, { applyLiteShims = false } = {}) {
  const reachable = new Set();
  const queue = [...roots];
  while (queue.length) {
    const file = queue.pop();
    if (reachable.has(file)) continue;
    const shimTarget = applyLiteShims ? LAZY_SHIM_SUBSTITUTIONS[file] : null;
    const node = shimTarget ? graph.nodes[shimTarget] : graph.nodes[file];
    if (!node) continue; // root not in graph (shouldn't happen for real roots) or unresolved edge
    reachable.add(file);
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) queue.push(ref.resolved);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.literal && fs.resolved) queue.push(fs.resolved);
    }
  }
  return reachable;
}

// Every bare-package specifier reachable from a given reachable-file set —
// used to answer "does this reachable subgraph actually import a heavy
// native package" without conflating it with a file that merely MENTIONS
// the package name in a comment.
export function collectExternalDeps(graph, reachableSet) {
  const deps = new Map(); // pkgName -> Set(files that import it)
  for (const file of reachableSet) {
    const node = graph.nodes[file];
    if (!node) continue;
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'package') {
          if (!deps.has(ref.resolved)) deps.set(ref.resolved, new Set());
          deps.get(ref.resolved).add(file);
        }
      }
    }
  }
  return deps;
}

export const HEAVY_LOCAL_PACKAGES = ['onnxruntime-node', '@huggingface/transformers'];

// Directory/file-based FIRST-PASS classification signal — deliberately
// coarse (directory alone is not proof; see the "grounded by graph" pass
// below, which can override this using real reachability facts). This
// mirrors packages/lite/build.mjs's own EXCLUDE_FILES/EXCLUDE_DIRS list —
// re-derived independently here (not imported from build.mjs) so this
// audit script has no dependency on the packaging tool's internals and
// double-checks it rather than trusting it blindly.
export const LOCAL_ONLY_PATH_PATTERNS = [
  /^src\/core\/onnx-embed\.js$/, /^src\/core\/onnx-runtime\.js$/, /^src\/core\/onnx-probe-runner\.js$/,
  /^src\/core\/onnx-provider-probe\.js$/, /^src\/core\/length-bucket\.js$/, /^src\/core\/ce-rerank\.js$/,
  /^src\/core\/ce-rerank-worker\.js$/, /^src\/core\/ollama\.js$/, /^src\/core\/ollama-models\.js$/,
  /^src\/indexer\/phases\/tag-onnx\.js$/, /^src\/indexer\/workers\/tag-onnx-worker\.js$/,
  /^src\/admin\/system\/ollama\.js$/, /^src\/admin\/api\/onnx\.js$/, /^src\/admin\/api\/ollama-models\.js$/,
];
export const COMPOSITION_FULL_PATTERNS = [
  /^src\/admin\/bootstrap\.js$/, /^src\/admin\/server-full\.js$/, /^src\/doctor\.js$/, /^src\/backfill-tags\.js$/,
  /^src\/backfill-entity-refs\.js$/, /^src\/sync\.js$/, /^src\/smoke\.js$/, /^src\/bootstrap-docs\.js$/,
];
export const CLOUD_ONLY_PATH_PATTERNS = [
  /^src\/core\/embedding-profile\/qdrant-cloud/, /^src\/admin\/system\/qdrant-cloud\.js$/,
  /^src\/admin\/api\/qdrant-cloud\.js$/, /^src\/core\/gemini-models\.js$/, /^src\/core\/generation\/gemini-provider\.js$/,
];
const LAZY_SHIM_PATTERNS = [/-lazy\.js$/, /-lazy\.lite\.js$/];

// packages/lite/build.mjs's REAL, COMPLETE EXCLUDE_DIRS (4 entries) and
// EXCLUDE_FILES (18 entries) — extracted verbatim from that file's own
// source (2026-08-01), not a partial re-derivation. Code review correctly
// flagged that the earlier version of this script's liteTarballStaged
// computation only checked LOCAL_ONLY_PATH_PATTERNS (14 files) plus 4
// directories, silently missing 8 of build.mjs's real 18 exclusions
// (admin/bootstrap.js, admin/server-full.js, doctor.js, backfill-tags.js,
// backfill-entity-refs.js, sync.js, smoke.js, bootstrap-docs.js — every
// one of COMPOSITION_FULL_PATTERNS above, none of which is local-runtime-
// coupled, all of which are still genuinely EXCLUDED from the Lite
// tarball) — so those 8 files were wrongly reported liteTarballStaged:
// true. Fixed by unioning BOTH pattern lists into the exclusion check,
// matching build.mjs's real EXCLUDE_FILES list file-for-file.
const EXCLUDE_DIRS = ['src/admin/ui-src/', 'src/mcp/', 'src/smoke/', 'src/test-fixtures/'];
const ALL_EXCLUDED_FILE_PATTERNS = [...LOCAL_ONLY_PATH_PATTERNS, ...COMPOSITION_FULL_PATTERNS];

function firstPassBucket(file) {
  if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(file))) return 'local';
  if (COMPOSITION_FULL_PATTERNS.some((p) => p.test(file))) return 'composition-full';
  if (CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(file))) return 'cloud';
  if (LAZY_SHIM_PATTERNS.some((p) => p.test(file))) return 'mixed'; // lazy wrappers are a real boundary seam, always reviewed by hand
  if (file === 'src/admin/server.js') return 'mixed'; // hosts BOTH createLiteApp (lite composition) and registerNeutralRoutes (shared)
  // admin/ui-src/*.js is OUTSIDE the Node.js import graph this script
  // traces (it is Vite/browser-side module code, never require()'d or
  // import()'d from any src/ Node.js file) — a plain reachability
  // classification cannot say anything about it at all. Hand-verified
  // instead (grep for onnx|ollama across every ui-src/*.js file, then
  // read each real hit in context): exactly 2 files contain a REAL
  // IS_LITE-guarded local/shared code split (global-settings-view.js's
  // documented ONNX-panel/Ollama-model-refresh guards; settings-view.js's
  // reindex-options branch reading #opt-onnx/#opt-llm-summaries/#opt-tags,
  // which would throw on a null DOM read in Lite's stripped HTML without
  // the guard) — genuinely `mixed`. jobs-view.js and collection-view.js
  // each have a couple of onnx/ollama substring hits too, but on
  // inspection both are PROVIDER-NEUTRAL, data-driven code (e.g.
  // collection-view.js's `isLocal = /onnx|ollama|local/i.test(denseProvider)`
  // just inspects whatever string the API returned — it has no ONNX/Ollama-
  // SPECIFIC branch of its own) — correctly `shared`, not `mixed`. Every
  // other ui-src/*.js file has zero onnx/ollama references at all.
  if (['src/admin/ui-src/global-settings-view.js', 'src/admin/ui-src/settings-view.js'].includes(file)) return 'mixed';
  if (file.startsWith('src/admin/ui-src/')) return 'shared';
  return null; // undetermined by pattern — graph facts decide
}

// Code review finding: a Full-only classification ("reachable from Full,
// never from Lite") was previously conflated with "local-runtime-coupled"
// under one 'local' bucket — misleading, since most of mcp/'s 14 files
// (11 of them, see below) are reachable ONLY from Full purely because
// Lite has no MCP entry point at all today, NOT because they import
// anything ONNX/Ollama-specific. Two independent axes, reported
// separately: `runtimeCoupling` ('local'|'cloud'|'none') answers "does
// this file's OWN direct-dependency set include a real ONNX/Ollama/heavy-
// native edge," computed from the graph, not from directory location.
// `classification` keeps its existing shared/local/cloud/mixed/etc.
// vocabulary for the top-level bucket (still useful, still what most
// consumers of this inventory want first), but a `local` classification
// caused purely by missing Lite entry-point coverage (Full-reachable,
// zero local-runtime edges of its own) is now distinguishable via
// runtimeCoupling: 'none' — see main()'s classification logic below,
// which checks the file's OWN local-only dependency edges (not just
// Full-vs-Lite reachability) before finalizing 'local'.
function computeRuntimeCoupling(graph, file) {
  const node = graph.nodes[file];
  if (!node) return 'none';
  const relDeps = [];
  for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
    for (const ref of group) {
      if (ref.kind === 'relative' && ref.resolved) relDeps.push(ref.resolved);
    }
  }
  for (const fs of node.forkSpawnCalls) {
    if (fs.resolved) relDeps.push(fs.resolved);
  }
  const ownDepsAreLocal = relDeps.some((d) => LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(d)));
  const ownDepsAreCloud = relDeps.some((d) => CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(d)));
  if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(file)) || ownDepsAreLocal) return 'local';
  if (CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(file)) || ownDepsAreCloud) return 'cloud';
  return 'none';
}

// Deterministic recommendedAction, computed from facts already gathered —
// never a hand-filled placeholder (code review finding: every one of the
// 236 prior entries had recommendedAction: null despite the artifact
// being presented as a complete per-module inventory). Four possible
// values, matching the JSON schema documented in the design doc's Part L:
// 'keep' (no action needed), 'split' (genuinely mixed, needs a real code
// split — see the design doc's §4 for the human-reviewed detail behind
// each), 'move' (correctly placed today but a candidate for physical
// relocation once a real shared/cloud/local directory structure exists —
// Phase 8 territory, not urgent), 'exclude' (should never be reachable
// from Lite and today correctly isn't).
function computeRecommendedAction(file, { classification, runtimeCoupling, liteReachable, liteTarballStaged }) {
  if (classification === 'mixed') return 'split';
  if (classification === 'composition-full' || classification === 'composition-lite') return 'keep';
  if (classification === 'local') {
    // Distinguishes the P2 finding precisely: a file that is Full-only
    // AND has zero local-runtime coupling of its own (most of mcp/'s 11
    // provider-neutral tool files) is a 'move' candidate (it could become
    // 'shared' once Lite gains an entry point that reaches it — no code
    // change needed in the file itself); a file with REAL local-runtime
    // coupling (onnxruntime-node/Ollama edges) is correctly 'exclude'.
    if (runtimeCoupling === 'none') return 'move';
    return liteReachable ? 'split' : 'exclude'; // liteReachable+local should never co-occur post-shim; 'split' flags it for review if it ever does
  }
  if (classification === 'cloud' || classification === 'shared') return 'keep';
  if (classification === 'unclear') return 'keep'; // e.g. the two test-only contract validators — see design doc §6.9
  return 'keep';
}

function main() {
  const graph = loadOrBuildGraph();

  const fullReachable = computeReachable(graph, FULL_ROOTS);
  // Union of every real file under packages/lite/lite-src/ (now genuine
  // graph nodes, not a hand-transcribed import list — see this file's own
  // header comment). Computed TWICE: liteReachablePreShim reflects real
  // src/ as it exists in the repo (what a naive "just stage everything
  // reachable" tool would see); liteReachable (post-shim) additionally
  // applies build.mjs's own *-lazy.js -> *-lazy.lite.js content
  // substitution, matching what ACTUALLY ships in the tarball. The gap
  // between the two sets is exactly the set of files the lazy-shim
  // mechanism is responsible for cutting — reported explicitly below, not
  // silently discarded.
  const liteSyntheticRoots = graph.files.filter((f) => f.startsWith(LITE_SRC_DIR));
  const liteReachablePreShim = computeReachable(graph, liteSyntheticRoots, { applyLiteShims: false });
  const liteReachable = computeReachable(graph, liteSyntheticRoots, { applyLiteShims: true });
  const shimCutFiles = [...liteReachablePreShim].filter((f) => !liteReachable.has(f)).sort();

  const fullExternalDeps = collectExternalDeps(graph, fullReachable);
  const liteExternalDeps = collectExternalDeps(graph, liteReachable);
  const liteExternalDepsPreShim = collectExternalDeps(graph, liteReachablePreShim);

  const liteHeavyDepsReachable = HEAVY_LOCAL_PACKAGES.filter((p) => liteExternalDeps.has(p));
  const fullHeavyDepsReachable = HEAVY_LOCAL_PACKAGES.filter((p) => fullExternalDeps.has(p));

  // Code review P2 finding: "cloud never imports local" was asserted in
  // the design doc's Part K list but never actually checked anywhere —
  // only Lite-reachability-excludes-local was checked. Real check: for
  // every CLOUD_ONLY_PATH_PATTERNS file, walk its OWN direct dependency
  // edges (not transitively — a direct violation is the meaningful unit
  // here, matching how the other direction-rules in this script work) and
  // flag any that resolve to a LOCAL_ONLY_PATH_PATTERNS file.
  const cloudFiles = graph.files.filter((f) => CLOUD_ONLY_PATH_PATTERNS.some((p) => p.test(f)));
  const cloudImportsLocalViolations = [];
  for (const file of cloudFiles) {
    const node = graph.nodes[file];
    const relDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) relDeps.push(ref.resolved);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.resolved) relDeps.push(fs.resolved);
    }
    for (const dep of relDeps) {
      if (LOCAL_ONLY_PATH_PATTERNS.some((p) => p.test(dep))) {
        cloudImportsLocalViolations.push({ from: file, to: dep });
      }
    }
  }

  const inventory = [];
  for (const file of graph.files) {
    if (file.startsWith(LITE_SRC_DIR)) continue; // handled in the composition-lite pass below, with entryPoints: ['lite'] instead of reachability-derived
    const node = graph.nodes[file];
    const inFull = fullReachable.has(file);
    const inLite = liteReachable.has(file);

    const directDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) directDeps.push(ref.resolved);
        else if (ref.kind === 'package') directDeps.push(`pkg:${ref.resolved}`);
      }
    }
    for (const fs of node.forkSpawnCalls) {
      if (fs.resolved) directDeps.push(fs.resolved);
    }

    let classification = firstPassBucket(file);
    if (!classification) {
      if (inFull && inLite) classification = 'shared';
      else if (inFull && !inLite) classification = 'local'; // reachable ONLY from Full's own graph traversal, never Lite's — see runtimeCoupling below for whether this is REALLY local-runtime-coupled or just missing Lite entry-point coverage (§6.6 of the design doc)
      else if (!inFull && inLite) classification = 'cloud'; // reachable only via Lite's synthetic roots (shouldn't normally happen since Full imports Lite's whole cloud surface too, but recorded honestly if found)
      else classification = 'unclear'; // reachable from neither traced root set — dead code, test-only helper, or genuinely orphaned
    }

    const runtimeCoupling = computeRuntimeCoupling(graph, file);

    // Two DISTINCT questions, deliberately not conflated (Part C's own
    // required distinction): "does build.mjs's STAGING step copy this
    // specific file's bytes into packages/lite/src/" (liteTarballStaged —
    // a pure exclude-list membership question, re-derived from
    // build.mjs's real, COMPLETE EXCLUDE_DIRS/EXCLUDE_FILES — 4 dirs, 18
    // files, verbatim, not a partial subset) vs. "is this file genuinely
    // REACHABLE from a real Lite entry point, post-lazy-shim-substitution"
    // (liteReachable, computed above — the thing that actually matters
    // for "can this code ever execute in Lite"). A file can be staged but
    // unreachable (dead weight in the tarball, not a safety problem) or —
    // the case that would actually matter — reachable without being
    // staged (impossible by construction here, since reachability is
    // computed FROM the same real src/ tree the staging list excludes
    // from, but the two are still reported as separate fields so this
    // invariant itself stays checkable rather than assumed).
    const inTarballDir = !EXCLUDE_DIRS.some((d) => file.startsWith(d));
    const inTarballFile = !ALL_EXCLUDED_FILE_PATTERNS.some((p) => p.test(file));
    // The three *.lite.js shim SOURCE files (core/ollama-lazy.lite.js,
    // core/onnx-embed-lazy.lite.js, indexer/phases/tag-onnx-lazy.lite.js)
    // are a real, cross-checked-against-the-actual-staged-tree exception:
    // build.mjs's substituteLazyShims() copies each one's CONTENT onto the
    // real module's path (e.g. core/ollama-lazy.js), then deletes the
    // separately-staged shim file under its own name — so the shim file
    // itself never survives staging under its own path, even though the
    // *.js file it targets (without .lite in the name) genuinely does.
    const isLazyShimSourceFile = /-lazy\.lite\.js$/.test(file);
    const liteTarballStaged = (inTarballDir && inTarballFile) && !isLazyShimSourceFile;

    const liteBrowserBundle = file.startsWith('src/admin/ui-src/');

    inventory.push({
      path: file,
      classification,
      runtimeCoupling,
      entryPoints: FULL_ROOTS.includes(file) ? ['full'] : [],
      directDependencies: [...new Set(directDeps)],
      fullReachable: inFull,
      liteReachable: inLite,
      liteReachablePreShim: liteReachablePreShim.has(file),
      liteTarballStaged,
      liteBrowserBundle,
      recommendedAction: computeRecommendedAction(file, { classification, runtimeCoupling, liteReachable: inLite, liteTarballStaged }),
    });
  }

  // packages/lite/lite-src/*.js — now real graph nodes (parsed by
  // build-import-graph.mjs alongside src/), appended here as explicit
  // composition-lite entries with their own real (not hand-transcribed)
  // directDependencies pulled straight from the graph.
  for (const liteSrcFile of liteSyntheticRoots) {
    const node = graph.nodes[liteSrcFile];
    const directDeps = [];
    for (const group of [node.staticImports, node.dynamicImports, node.requireCalls]) {
      for (const ref of group) {
        if (ref.kind === 'relative' && ref.resolved) directDeps.push(ref.resolved);
        else if (ref.kind === 'package') directDeps.push(`pkg:${ref.resolved}`);
      }
    }
    inventory.push({
      path: liteSrcFile,
      classification: 'composition-lite',
      runtimeCoupling: 'none',
      entryPoints: ['lite'],
      directDependencies: [...new Set(directDeps)],
      fullReachable: false,
      liteReachable: true,
      liteReachablePreShim: true,
      liteTarballStaged: true, // packages/lite/package.json's "files" includes lite-src/ unconditionally
      liteBrowserBundle: false,
      recommendedAction: 'keep',
    });
  }

  mkdirSync(ARTIFACTS_DIR, { recursive: true });
  writeFileSync(join(ARTIFACTS_DIR, 'full-lite-module-inventory.json'), JSON.stringify(inventory, null, 2), 'utf-8');

  const counts = inventory.reduce((acc, m) => { acc[m.classification] = (acc[m.classification] ?? 0) + 1; return acc; }, {});
  const runtimeCouplingCounts = inventory.reduce((acc, m) => { acc[m.runtimeCoupling] = (acc[m.runtimeCoupling] ?? 0) + 1; return acc; }, {});
  // The precise number code review's P2 finding asked for: of the files
  // classified 'local', how many are ACTUALLY local-runtime-coupled vs.
  // merely Full-only-with-no-Lite-entry-point (e.g. 11 of mcp/'s 14
  // files).
  const localClassified = inventory.filter((m) => m.classification === 'local');
  const localGenuinelyCoupled = localClassified.filter((m) => m.runtimeCoupling === 'local').length;
  const localFullOnlyNoCoupling = localClassified.filter((m) => m.runtimeCoupling === 'none').length;

  const liteHeavyDepsReachablePreShim = HEAVY_LOCAL_PACKAGES.filter((p) => liteExternalDepsPreShim.has(p));

  console.log(`[audit] classified ${inventory.length} modules`);
  console.log('[audit] classification counts:', JSON.stringify(counts, null, 2));
  console.log('[audit] runtimeCoupling counts:', JSON.stringify(runtimeCouplingCounts, null, 2));
  console.log(`[audit] of ${localClassified.length} 'local'-classified modules: ${localGenuinelyCoupled} genuinely local-runtime-coupled, ${localFullOnlyNoCoupling} Full-only with NO local-runtime coupling of their own (mostly mcp/ — see design doc §6.6)`);
  console.log(`[audit] Full-reachable: ${fullReachable.size}`);
  console.log(`[audit] Lite-reachable PRE-shim (real src/, no build.mjs substitution): ${liteReachablePreShim.size}`);
  console.log(`[audit] Lite-reachable POST-shim (matches actual shipped tarball): ${liteReachable.size}`);
  console.log(`[audit] files the lazy-shim substitution removes from Lite's reachable set: ${shimCutFiles.length} -> ${JSON.stringify(shimCutFiles)}`);
  console.log(`[audit] heavy local packages reachable from LITE PRE-shim: ${JSON.stringify(liteHeavyDepsReachablePreShim)}`);
  console.log(`[audit] heavy local packages reachable from LITE POST-shim (actual tarball reality): ${JSON.stringify(liteHeavyDepsReachable)}`);
  console.log(`[audit] heavy local packages reachable from FULL roots: ${JSON.stringify(fullHeavyDepsReachable)}`);
  if (liteHeavyDepsReachablePreShim.length) {
    for (const dep of liteHeavyDepsReachablePreShim) {
      console.log(`  [pre-shim only] ${dep} reachable via: ${[...liteExternalDepsPreShim.get(dep)].join(', ')}`);
    }
  }
  if (liteHeavyDepsReachable.length) {
    for (const dep of liteHeavyDepsReachable) {
      console.log(`  [!! POST-SHIM — real problem] ${dep} reachable via: ${[...liteExternalDeps.get(dep)].join(', ')}`);
    }
  } else {
    console.log('  [ok] zero heavy local packages reachable POST-shim — matches the shipped tarball\'s actual dependency list.');
  }
  console.log(`[audit] cloud-imports-local violations: ${cloudImportsLocalViolations.length}${cloudImportsLocalViolations.length ? ' -> ' + JSON.stringify(cloudImportsLocalViolations) : ' (none — cloud correctly never imports local)'}`);

  writeFileSync(join(ARTIFACTS_DIR, 'full-lite-reachability-summary.json'), JSON.stringify({
    fullRoots: FULL_ROOTS,
    liteSyntheticRoots,
    lazyShimSubstitutions: LAZY_SHIM_SUBSTITUTIONS,
    fullReachableCount: fullReachable.size,
    liteReachablePreShimCount: liteReachablePreShim.size,
    liteReachableCount: liteReachable.size,
    shimCutFiles,
    fullReachableFiles: [...fullReachable].sort(),
    liteReachablePreShimFiles: [...liteReachablePreShim].sort(),
    liteReachableFiles: [...liteReachable].sort(),
    fullExternalDeps: Object.fromEntries([...fullExternalDeps.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteExternalDepsPreShim: Object.fromEntries([...liteExternalDepsPreShim.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteExternalDeps: Object.fromEntries([...liteExternalDeps.entries()].map(([k, v]) => [k, [...v].sort()])),
    liteHeavyDepsReachablePreShim,
    liteHeavyDepsReachable,
    fullHeavyDepsReachable,
    cloudImportsLocalViolations,
    classificationCounts: counts,
    runtimeCouplingCounts,
    localGenuinelyCoupled,
    localFullOnlyNoCoupling,
  }, null, 2), 'utf-8');
  console.log(`[audit] wrote full-lite-reachability-summary.json and full-lite-module-inventory.json`);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
