#!/usr/bin/env node
// packages/lite/build.mjs — the Semidex Lite "prepack" build step. Stages a
// curated subset of the repo's src/ tree into packages/lite/src/ (gitignored,
// regenerated by this script every time), substitutes every *-lazy.js
// module (core/ollama-lazy.js, core/onnx-embed-lazy.js) with its
// Lite-specific *-lazy.lite.js shim, copies the prebuilt Lite admin UI into
// packages/lite/dist/admin-ui/, and then runs a five-part closure validator
// against the STAGED tree — never the repo's live src/ — so the
// validator's result reflects exactly what will ship in the tarball.
//
// Parser: acorn (root devDependency — NOT a Lite runtime dependency; see
// package.json's own "dependencies" list, which excludes it entirely).
// Every staged .js file is PARSED, never executed, into a real ESTree AST
// and walked with acorn-walk for: import/export-from declarations, literal
// dynamic import() expressions, require()/createRequire() calls, and
// fork()/spawn() calls. No source-regex scanning is used as the authority
// for any of the five checks below — regexes are not used at all in this
// file.
import { parse } from 'acorn';
import { simple as walkSimple } from 'acorn-walk';
import {
  existsSync, mkdirSync, rmSync, readFileSync, writeFileSync, readdirSync, statSync, copyFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve, extname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const LITE_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(LITE_DIR, '..', '..');
const REPO_SRC = join(REPO_ROOT, 'src');
const STAGED_SRC = join(LITE_DIR, 'src');
const STAGED_DIST = join(LITE_DIR, 'dist');
const LITE_SRC = join(LITE_DIR, 'lite-src');

// ── Curated inclusion/exclusion list ────────────────────────────────────────
//
// Exclusion rule (see the plan): drop a file only if it (a) pulls a heavy
// native dep OR is a local-only module Lite never reaches, AND (b) has no
// static importer among KEPT files. Every exclusion below has been verified
// against the real import graph (see docs/design/semidex-lite-package-
// boundary.md) — this is not a guess list, it is the audited result.
const EXCLUDE_DIRS = [
  'admin/ui-src', // raw UI source — the BUILT dist/admin-ui/ ships instead
  'mcp', // separate entry point, not part of the Lite cloud API/CLI surface
  'smoke', // dev-only test harness, never shipped
  'test-fixtures', // smoke-test-only fixtures (src/smoke/sections/17-pdf-fixture.js is the only consumer, and smoke/ itself is already excluded above)
];

const EXCLUDE_FILES = [
  // Local ONNX runtime — never statically imported by any kept file after
  // the onnx-embed-lazy.js edge cut (core/embeddings.js) and the
  // tag-onnx-lazy.js edge cut (indexer/run.js).
  'core/onnx-embed.js',
  'core/onnx-runtime.js',
  'core/onnx-probe-runner.js',
  'core/onnx-provider-probe.js',
  'core/length-bucket.js', // ONNX-batching-only helper, no non-ONNX importer
  'core/ce-rerank.js',
  'core/ce-rerank-worker.js',
  'indexer/phases/tag-onnx.js',
  'indexer/workers/tag-onnx-worker.js',
  // Local-only Ollama modules — excluded now that Refactor 1 (ollama-lazy.js,
  // substituted below) and Refactor 3 (jobs.js/generation-models.js/system.js
  // DI splits) have cut every static edge onto these from kept files.
  //
  // core/generation/ollama-provider.js is NOT in this list — it is kept.
  // generation/registry.js's BACKENDS map references createOllamaProvider
  // unconditionally (only ever CALLED when backend === 'ollama'), so it
  // must be a real staged file, not excluded. It is safe to keep because it
  // itself imports from ../ollama-lazy.js (substituted below), never
  // ../ollama.js directly — merely importing/keeping it in the closure
  // never pulls core/ollama.js in, and its methods are only reachable if
  // registry.js's BACKENDS.ollama were actually selected, which Lite's CLI
  // hard pin (SEMIDEX_GENERATION_BACKEND=gemini) prevents.
  'core/ollama.js',
  'core/ollama-models.js',
  'admin/system/ollama.js',
  // Full-only admin composition pieces — Lite never registers these routes,
  // and after Refactor 3 no kept file statically imports them.
  'admin/api/onnx.js',
  'admin/api/ollama-models.js',
  // admin/server-full.js contains createApp() (the FULL composition root)
  // and its four Ollama/ONNX-only static imports — split out of
  // admin/server.js specifically so Lite can stage server.js (which owns
  // createLiteApp(), registerNeutralRoutes(), createHttpServer()) without
  // also staging this file. See server-full.js's own header comment.
  'admin/server-full.js',
  // Full-Semidex-only entry points/composition roots — Lite has its own
  // equivalents (packages/lite/lite-src/serve-lite.js uses
  // createLiteApp()/registerNeutralRoutes() from the STILL-staged
  // admin/server.js, but never imports admin/bootstrap.js itself;
  // packages/lite/lite-src/doctor-lite.js/index-lite.js replace doctor.js/
  // the CLI indexer wrapper; backfill-tags.js/backfill-entity-refs.js/
  // sync.js/smoke.js/bootstrap-docs.js are full-Semidex dev/maintenance
  // tooling with no Lite equivalent).
  'admin/bootstrap.js',
  'doctor.js',
  'backfill-tags.js',
  'backfill-entity-refs.js',
  'sync.js',
  'smoke.js',
  'bootstrap-docs.js',
  // core/ollama-lazy.js and core/onnx-embed-lazy.js are NOT excluded from
  // the walk (they ARE staged) but are CONTENT-substituted with their
  // *.lite.js shims below — see substituteLazyShims().
];
const EXCLUDE_FILE_SET = new Set(EXCLUDE_FILES);

function shouldExcludeDir(relDir) {
  const normalized = relDir.replace(/\\/g, '/');
  return EXCLUDE_DIRS.some((d) => normalized === d || normalized.startsWith(`${d}/`));
}

function shouldExcludeFile(relFile) {
  const normalized = relFile.replace(/\\/g, '/');
  return EXCLUDE_FILE_SET.has(normalized);
}

// ── Step 1: stage src/ ───────────────────────────────────────────────────────

function listAllFiles(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (shouldExcludeDir(relative(base, full))) continue;
      out.push(...listAllFiles(full, base));
    } else {
      out.push(rel);
    }
  }
  return out;
}

function stageSrc() {
  rmSync(STAGED_SRC, { recursive: true, force: true });
  mkdirSync(STAGED_SRC, { recursive: true });
  const allFiles = listAllFiles(REPO_SRC);
  const staged = [];
  for (const rel of allFiles) {
    if (extname(rel) === '.js' && shouldExcludeFile(rel)) continue;
    const src = join(REPO_SRC, rel);
    const dest = join(STAGED_SRC, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(src, dest);
    staged.push(rel.replace(/\\/g, '/'));
  }
  return staged;
}

// ── Step 2: substitute every *-lazy.js module with its Lite shim ───────────
//
// Each entry's real module (e.g. core/ollama-lazy.js) does
// `await import('./<excluded-module>.js')` — a literal dynamic-import
// target that would fail check #2 below (and throw ERR_MODULE_NOT_FOUND at
// runtime if ever reached), since the module it targets is excluded from
// the Lite tarball. Staging the paired `.lite.js` shim's CONTENT at the
// real module's exact path means every caller's import specifier is
// unchanged — no caller needs to know which variant it is running against.
const LAZY_SHIM_SUBSTITUTIONS = [
  { real: 'core/ollama-lazy.js', shim: 'core/ollama-lazy.lite.js' },
  { real: 'core/onnx-embed-lazy.js', shim: 'core/onnx-embed-lazy.lite.js' },
  { real: 'indexer/phases/tag-onnx-lazy.js', shim: 'indexer/phases/tag-onnx-lazy.lite.js' },
];

function substituteLazyShims() {
  for (const { real, shim } of LAZY_SHIM_SUBSTITUTIONS) {
    const shimSrc = readFileSync(join(REPO_SRC, ...shim.split('/')), 'utf-8');
    writeFileSync(join(STAGED_SRC, ...real.split('/')), shimSrc);
    // The shim's own separate staged copy is removed — it has done its job
    // (its content is now AT the real module's path) and leaving the
    // original around would be a second, unused, near-duplicate file in
    // the shipped package for no reason.
    rmSync(join(STAGED_SRC, ...shim.split('/')), { force: true });
  }
}

// ── Step 3: copy the prebuilt Lite admin UI ─────────────────────────────────

function stageDist({
  source = join(LITE_DIR, '..', '..', 'dist', 'admin-ui-lite'),
  destination = STAGED_DIST,
} = {}) {
  rmSync(destination, { recursive: true, force: true });
  if (!existsSync(source)) {
    throw new Error(`[build] ${relative(REPO_ROOT, source)} does not exist. Run \`npm run admin:build:lite\` before packaging Semidex Lite.`);
  }
  mkdirSync(join(destination, 'admin-ui'), { recursive: true });
  copyDirRecursive(source, join(destination, 'admin-ui'));
}

function copyDirRecursive(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const s = join(src, entry);
    const d = join(dest, entry);
    if (statSync(s).isDirectory()) copyDirRecursive(s, d);
    else copyFileSync(s, d);
  }
}

// ── AST parsing helpers ──────────────────────────────────────────────────────

function parseFile(absPath) {
  const src = readFileSync(absPath, 'utf-8');
  return parse(src, { sourceType: 'module', ecmaVersion: 'latest', allowImportExportEverywhere: true });
}

// Resolves a relative or absolute-in-package specifier against `fromFile`
// (a path relative to STAGED_SRC) to a path relative to STAGED_SRC, trying
// the extensionless/.js/index.js resolution Node's ESM loader itself uses.
function resolveRelativeSpecifier(specifier, fromFileRel) {
  if (!specifier.startsWith('.')) return null; // not a relative import
  const fromDir = dirname(join(STAGED_SRC, fromFileRel));
  let candidate = resolve(fromDir, specifier);
  const tryPaths = [candidate, `${candidate}.js`, join(candidate, 'index.js')];
  for (const p of tryPaths) {
    if (existsSync(p) && statSync(p).isFile()) return relative(STAGED_SRC, p).replace(/\\/g, '/');
  }
  return null; // did not resolve to any staged file
}

/**
 * Extracts every static import/export-from specifier, every literal dynamic
 * import() specifier, every require()/createRequire()-bound-require()
 * literal specifier, and every literal fork()/spawn() first argument (plus
 * `new URL(literal, import.meta.url)` expressions assigned to a const that
 * later flows into fork()/spawn() — the pattern admin/jobs/registry.js and
 * core/ce-rerank.js/tag-onnx.js all use for their child-process entry path).
 */
function extractReferences(ast) {
  const staticImports = [];
  const dynamicImports = []; // { specifier, literal: bool }
  const requireCalls = [];
  const forkSpawnCalls = []; // { callee: 'fork'|'spawn', arg, literal: bool }
  const urlPathConsts = new Map(); // identifier name -> literal path string

  // Track which local identifiers are bound to node:child_process's
  // fork/spawn (possibly renamed on import) and to Node's require via
  // createRequire(import.meta.url).
  const childProcessImportNames = new Set(); // local name -> 'fork' | 'spawn'
  const childProcessLocalToReal = new Map();
  const requireLocalNames = new Set();

  walkSimple(ast, {
    ImportDeclaration(node) {
      staticImports.push(node.source.value);
      if (node.source.value === 'node:child_process' || node.source.value === 'child_process') {
        for (const spec of node.specifiers) {
          if (spec.type === 'ImportSpecifier' && (spec.imported.name === 'fork' || spec.imported.name === 'spawn')) {
            childProcessImportNames.add(spec.local.name);
            childProcessLocalToReal.set(spec.local.name, spec.imported.name);
          }
        }
      }
    },
    ExportNamedDeclaration(node) {
      if (node.source) staticImports.push(node.source.value);
    },
    ExportAllDeclaration(node) {
      staticImports.push(node.source.value);
    },
    ImportExpression(node) {
      if (node.source.type === 'Literal') {
        dynamicImports.push({ specifier: node.source.value, literal: true });
      } else {
        dynamicImports.push({ specifier: null, literal: false });
      }
    },
    VariableDeclarator(node) {
      // const require = createRequire(import.meta.url);
      if (
        node.init?.type === 'CallExpression'
        && node.init.callee.type === 'Identifier'
        && node.init.callee.name === 'createRequire'
        && node.id.type === 'Identifier'
      ) {
        requireLocalNames.add(node.id.name);
      }
      // const WORKER_PATH = join(__dirname, '../workers/x.js') or
      // fileURLToPath(new URL('../x.js', import.meta.url)) — capture the
      // literal relative path argument for later fork()/spawn() tracing.
      if (node.id.type === 'Identifier') {
        const literalPath = findLiteralRelativePathArg(node.init);
        if (literalPath) urlPathConsts.set(node.id.name, literalPath);
      }
    },
    CallExpression(node) {
      const callee = node.callee;
      // require('literal') or requireLocalVar('literal')
      if (
        (callee.type === 'Identifier' && (callee.name === 'require' || requireLocalNames.has(callee.name)))
        && node.arguments[0]?.type === 'Literal'
      ) {
        requireCalls.push(node.arguments[0].value);
      }
      // fork('literal', ...) / spawn('literal', ...) / fork(constVar, ...) —
      // constVar resolved against urlPathConsts if it was captured above.
      if (callee.type === 'Identifier' && childProcessImportNames.has(callee.name)) {
        const real = childProcessLocalToReal.get(callee.name);
        const arg = node.arguments[0];
        if (arg?.type === 'Literal') {
          forkSpawnCalls.push({ callee: real, arg: arg.value, literal: true });
        } else if (arg?.type === 'Identifier' && urlPathConsts.has(arg.name)) {
          forkSpawnCalls.push({ callee: real, arg: urlPathConsts.get(arg.name), literal: true });
        } else if (arg?.type === 'Identifier') {
          // Not traced to a literal path — could be process.execPath (spawn
          // the CURRENT Node binary, not a repo-relative script) or another
          // dynamic value. Only flag as non-literal if it's clearly NOT
          // process.execPath (the one legitimate "spawn a fresh Node
          // process with an explicit entry-file second argument" pattern).
          forkSpawnCalls.push({ callee: real, arg: arg.name, literal: false });
        } else {
          forkSpawnCalls.push({ callee: real, arg: null, literal: false });
        }
      }
    },
  });

  return { staticImports, dynamicImports, requireCalls, forkSpawnCalls };
}

// Recognizes fileURLToPath(new URL('literal', import.meta.url)) and
// join(__dirname, 'literal') shapes, returning the literal relative-path
// argument if found, else null. Does not attempt to resolve __dirname's own
// value — callers only need the literal fragment to check it resolves to a
// staged file relative to the file currently being parsed.
function findLiteralRelativePathArg(node) {
  if (!node || node.type !== 'CallExpression') return null;
  // fileURLToPath(new URL('...', import.meta.url))
  if (node.callee.type === 'Identifier' && node.callee.name === 'fileURLToPath') {
    const inner = node.arguments[0];
    if (inner?.type === 'NewExpression' && inner.callee.name === 'URL' && inner.arguments[0]?.type === 'Literal') {
      return inner.arguments[0].value;
    }
  }
  // join(__dirname, '...') or join(someDir, '...literal...')
  if (node.callee.type === 'Identifier' && node.callee.name === 'join') {
    const litArg = node.arguments.find((a) => a.type === 'Literal' && typeof a.value === 'string' && a.value.includes('/'));
    if (litArg) return litArg.value;
  }
  return null;
}

// ── Step 4: the five-part closure validator ─────────────────────────────────

function runValidator(stagedFiles) {
  const errors = [];
  const pkg = JSON.parse(readFileSync(join(LITE_DIR, 'package.json'), 'utf-8'));
  const declaredDeps = new Set(Object.keys(pkg.dependencies ?? {}));
  const jsFiles = stagedFiles.filter((f) => f.endsWith('.js'));

  for (const relFile of jsFiles) {
    const absPath = join(STAGED_SRC, relFile);
    let ast;
    try {
      ast = parseFile(absPath);
    } catch (err) {
      errors.push(`[parse] ${relFile}: ${err.message}`);
      continue;
    }
    const refs = extractReferences(ast);
    const fromDir = dirname(relFile);

    // Check 1: static imports/export-from must resolve to a staged file OR
    // a bare specifier declared in dependencies (checked together with #4).
    for (const specifier of refs.staticImports) {
      checkSpecifier(specifier, relFile, 'static import', errors, declaredDeps);
    }

    // Check 2: literal dynamic imports must resolve to a staged file or a
    // declared dependency. Non-literal dynamic imports cannot be statically
    // verified — flagged as a WARNING via a distinct error prefix so the
    // build surfaces them for manual review rather than silently trusting
    // them (the plan requires no unverifiable escape hatch, but a
    // non-literal import() with no further specifier information genuinely
    // cannot be resolved by any static tool — this is reported, not
    // silently passed).
    for (const dyn of refs.dynamicImports) {
      if (!dyn.literal) {
        errors.push(`[dynamic-import:non-literal] ${relFile}: import() with a non-literal specifier cannot be statically verified — replace with a literal or a fully enumerated map.`);
        continue;
      }
      checkSpecifier(dyn.specifier, relFile, 'dynamic import', errors, declaredDeps);
    }

    // require()/createRequire()-bound require() literal specifiers — same
    // resolution rule as static imports.
    for (const specifier of refs.requireCalls) {
      checkSpecifier(specifier, relFile, 'require()', errors, declaredDeps);
    }

    // Check 3: fork()/spawn() literal path arguments must resolve to a
    // staged file. No "intentionally absent and unreachable" allow-list —
    // if a fork/spawn target isn't staged, this is an error, full stop. A
    // non-literal fork/spawn argument named exactly `process` combined with
    // `.execPath` (i.e. spawning the current Node binary itself, with the
    // real entry file passed as an explicit second array argument that is
    // ITSELF then checked) is the one recognized safe pattern
    // (admin/jobs/registry.js's own `spawnFn(process.execPath, [INDEXER_ENTRY, path], ...)`)
    // — INDEXER_ENTRY was already resolved via findLiteralRelativePathArg
    // and IS checked here as a literal.
    for (const call of refs.forkSpawnCalls) {
      if (!call.literal) {
        errors.push(`[${call.callee}:non-literal] ${relFile}: ${call.callee}() first argument could not be statically resolved to a literal path — no absent-fork-path exception exists; either make the target resolvable or gate/remove this call for Lite.`);
        continue;
      }
      const resolved = resolveRelativeSpecifier(call.arg, relFile);
      if (!resolved) {
        errors.push(`[${call.callee}:missing-target] ${relFile}: ${call.callee}('${call.arg}') does not resolve to any staged file.`);
      }
    }
  }

  return errors;

  function checkSpecifier(specifier, relFile, kind, errorsOut, deps) {
    if (specifier.startsWith('.')) {
      const resolved = resolveRelativeSpecifier(specifier, relFile);
      if (!resolved) {
        errorsOut.push(`[${kind}:missing-target] ${relFile}: "${specifier}" does not resolve to any staged file.`);
      }
      return;
    }
    if (specifier.startsWith('node:') || NODE_BUILTINS.has(specifier)) return; // Node builtin — always fine
    // Bare package specifier — Check 4: must be declared in dependencies.
    const pkgName = specifier.startsWith('@')
      ? specifier.split('/').slice(0, 2).join('/')
      : specifier.split('/')[0];
    if (!deps.has(pkgName)) {
      errorsOut.push(`[bare-specifier:undeclared] ${relFile}: imports "${specifier}" (package "${pkgName}") which is not in packages/lite/package.json's dependencies.`);
    }
  }
}

const NODE_BUILTINS = new Set([
  'fs', 'path', 'url', 'crypto', 'child_process', 'module', 'util', 'os', 'http', 'https', 'stream', 'events', 'zlib', 'buffer',
]);

// Check 5: staged dist/admin-ui/ must contain no ONNX/Ollama control
// markup/text — a real content scan of the built HTML/JS output (not the
// AST walker above, which only applies to .js source files).
function checkUiAssets(uiDir = join(STAGED_DIST, 'admin-ui')) {
  const errors = [];
  if (!existsSync(uiDir)) {
    return [`[ui-asset:missing] ${relative(LITE_DIR, uiDir)} does not exist.`];
  }
  const indexPath = join(uiDir, 'index.html');
  if (!existsSync(indexPath)) {
    errors.push('[ui-asset:missing] dist/admin-ui/index.html does not exist.');
  }
  const FORBIDDEN_MARKERS = [
    // Local-only setting keys (concrete field names, not shared
    // visibleWhen/dynamicOptions infrastructure).
    'ONNX_EXECUTION_PROVIDER', 'ONNXRUNTIME_NODE_PATH', 'OLLAMA_URL', 'GENERATION_DEVICE',
    'ONNX_BATCH_SIZE', 'ONNX_CUDA_STRICT', 'TAG_ONNX_MODEL', 'TAG_ONNX_THREADS', 'TAG_ONNX_ALLOW_DOWNLOAD',
    // Local-only HTML template ids.
    'tpl-gs-onnx-probe-panel',
    // Local-only API route strings — a leaked route string in the JS
    // bundle would mean the Lite UI could still attempt to call a route
    // createLiteApp() never registers (a 404 at runtime, but proof the
    // dead-code path was not actually eliminated).
    '/api/system/onnx-probe', '/api/ollama-models', '/api/system/ollama-status',
  ];
  const files = listAllFiles(uiDir).filter((f) => /\.(html|js|css)$/.test(f));
  if (files.length === 0) {
    errors.push('[ui-asset:empty] dist/admin-ui contains no HTML, JavaScript, or CSS assets.');
  }
  if (existsSync(indexPath)) {
    const indexHtml = readFileSync(indexPath, 'utf-8');
    const assetPattern = /(?:src|href)=["']([^"']+)["']/g;
    for (const match of indexHtml.matchAll(assetPattern)) {
      const reference = match[1];
      if (/^(?:[a-z]+:|\/\/|#|data:)/i.test(reference)) continue;
      const assetPath = join(uiDir, reference.replace(/^\//, '').split(/[?#]/, 1)[0]);
      if (!existsSync(assetPath)) {
        errors.push(`[ui-asset:missing-reference] dist/admin-ui/index.html references missing asset "${reference}".`);
      }
    }
  }
  for (const rel of files) {
    const content = readFileSync(join(uiDir, rel), 'utf-8');
    for (const marker of FORBIDDEN_MARKERS) {
      if (content.includes(marker)) {
        errors.push(`[ui-asset:forbidden-marker] dist/admin-ui/${rel}: contains "${marker}" — local-only control leaked into the Lite UI build.`);
      }
    }
  }
  return errors;
}

// ── Main ──────────────────────────────────────────────────────────────────

function main() {
  console.log('[build] staging src/ ...');
  const staged = stageSrc();
  console.log(`[build] staged ${staged.length} files`);

  console.log('[build] substituting *-lazy.js modules with their Lite shims ...');
  substituteLazyShims();

  console.log('[build] staging dist/admin-ui/ ...');
  stageDist();

  console.log('[build] running the five-part closure validator ...');
  const staticErrors = runValidator(listAllFiles(STAGED_SRC).map((f) => f.replace(/\\/g, '/')));
  const uiErrors = checkUiAssets();
  const allErrors = [...staticErrors, ...uiErrors];

  if (allErrors.length > 0) {
    console.error(`\n[build] FAILED — ${allErrors.length} closure violation(s):\n`);
    for (const e of allErrors) console.error(`  ${e}`);
    process.exitCode = 1;
    return;
  }

  console.log(`[build] OK — ${staged.length} files staged, closure validated clean.`);
}

// Only run when executed directly (npm's prepack hook) — importing this
// module for testing (e.g. to call runValidator() against a fixture tree)
// must not have a side effect.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}

export { extractReferences, parseFile, resolveRelativeSpecifier, runValidator, checkUiAssets, listAllFiles, stageSrc, substituteLazyShims, stageDist };
