#!/usr/bin/env node
// packages/lite/build.mjs — the Semidex Lite "prepack" build step. Stages a
// curated subset of the repo's src/ tree into packages/lite/src/ (gitignored,
// regenerated by this script every time), copies the prebuilt Lite admin UI
// into packages/lite/dist/admin-ui/, and then runs a five-part closure
// validator against the STAGED tree — never the repo's live src/ — so the
// validator's result reflects exactly what will ship in the tarball.
//
// No *-lazy.js content substitution step (code review, round 4 — removed;
// see EXCLUDE_FILES's own comment on core/ollama-lazy.js/
// core/onnx-embed-lazy.js/indexer/phases/tag-onnx-lazy.js for why: after
// indexer/index.js was split into index-full.js/index-lite.js and every
// other former consumer migrated to explicit capability injection with no
// real-module default of its own, nothing left in the KEPT Lite closure
// imports any of the three real *-lazy.js modules at all — they, and their
// *.lite.js shim siblings, are simply excluded from staging outright, the
// same as any other local-only file. The *.lite.js shim files themselves
// are dead code now (no build step or runtime import reaches them) but are
// left in src/ rather than deleted, since removing them outright is a
// separate cleanup decision outside this fix's own scope.
//
// Parser: acorn (root devDependency — NOT a Lite runtime dependency; see
// package.json's own "dependencies" list, which excludes it entirely).
// Every staged .js file is PARSED, never executed, into a real ESTree AST
// and walked with acorn-walk for: import/export-from declarations, literal
// dynamic import() expressions, require()/createRequire() calls, and
// fork()/spawn() calls. No source-regex scanning is used as the authority
// for any of the five checks below — regexes are not used at all in this
// file.
import { parse } from 'acorn';
import { simple as walkSimple, ancestor as walkAncestor } from 'acorn-walk';
import {
  existsSync, mkdirSync, rmSync, readFileSync, readdirSync, statSync, copyFileSync,
} from 'node:fs';
import { dirname, join, relative, resolve, extname } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const LITE_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(LITE_DIR, '..', '..');
const REPO_SRC = join(REPO_ROOT, 'src');
const STAGED_SRC = join(LITE_DIR, 'src');
const STAGED_DIST = join(LITE_DIR, 'dist');
const LITE_SRC = join(LITE_DIR, 'lite-src');

// ── Curated inclusion/exclusion list ────────────────────────────────────────
//
// Exclusion rule (see the plan): drop a file only if it (a) pulls a heavy
// native dep OR is a local-only module Lite never reaches, AND (b) has no
// static importer among KEPT files. Every exclusion below has been verified
// against the real import graph (see docs/design/semidex-lite-package-
// boundary.md) — this is not a guess list, it is the audited result.
const EXCLUDE_DIRS = [
  // admin/ui-src/ (Phase 8B Step 7C: only the composition-owned remainder —
  // entries/, index.html, lite-entry/, partials/lite/ — still lives here;
  // the shared/local UI source trees below are excluded via their own
  // physical location instead) — the BUILT dist/admin-ui-lite/ ships as
  // static assets via stageDist() instead of any raw UI source.
  'admin/ui-src',
  // shared/admin/ui-src/ (Phase 8B Step 7C — physically relocated from
  // admin/ui-src/) is genuinely Lite-reachable UI *source*, but Lite ships
  // the BUILT dist/admin-ui-lite/ output instead (via stageDist()), same
  // rule as admin/ui-src/ above — never the raw .js/.html/.css source.
  'shared/admin/ui-src',
  // local/admin/ui-src/ (Phase 8B Step 7C) is local-only UI source; already
  // covered by the blanket 'local' entry below, listed here only for
  // documentation symmetry with the two entries above.
  'mcp', // separate entry point, not part of the Lite cloud API/CLI surface
  'smoke', // dev-only test harness, never shipped
  'test-fixtures', // smoke-test-only fixtures (src/smoke/sections/17-pdf-fixture.js is the only consumer, and smoke/ itself is already excluded above)
  'local', // Phase 8B Steps 2-4 and 7C — the physically relocated local-runtime tree (local/core/: onnx-embed.js, onnx-runtime.js, onnx-probe-runner.js, onnx-provider-probe.js, length-bucket.js, ollama.js, ollama-models.js; local/indexer/phases/tag-onnx.js; local/indexer/workers/tag-onnx-worker.js; local/admin/: api/onnx.js, api/ollama-models.js, system/ollama.js, ui-src/local-features.js, ui-src/partials/full/*; and any future local-runtime file moved here) — excluded by directory rather than by individual EXCLUDE_FILES entry, since every file under this directory is local-only by construction of where it physically lives.
];

const EXCLUDE_FILES = [
  // Local ONNX EMBEDDING runtime (onnx-embed.js, onnx-runtime.js,
  // onnx-probe-runner.js, onnx-provider-probe.js, length-bucket.js) is no
  // longer listed here individually — Phase 8B Step 2 physically relocated
  // all five to local/core/, so EXCLUDE_DIRS's own 'local' entry now
  // excludes them by directory. Never statically imported by any kept file
  // after the onnx-embed-lazy.js edge cut (core/embeddings.js).
  'core/ce-rerank.js',
  'core/ce-rerank-worker.js',
  // core/rerank-provider.js (code review, Phase 8B Step 6 second pass, P1
  // fix): the one real RerankCapability factory — imports ce-rerank.js
  // directly. Its only real consumer is mcp/server.js (already excluded
  // above, 'mcp' — Lite ships no MCP server), so it would otherwise be a
  // dangling static import onto an excluded file, exactly the closure
  // violation class this validator exists to catch.
  'core/rerank-provider.js',
  // Local ONNX TAG GENERATION runtime (tag-onnx.js, tag-onnx-worker.js) is
  // no longer listed here individually either — Phase 8B Step 4 physically
  // relocated both to local/indexer/phases/ and local/indexer/workers/, so
  // EXCLUDE_DIRS's own 'local' entry now excludes them by directory, the
  // same as the ONNX embedding and Ollama runtimes before them (Phase 8B
  // Steps 2-3).
  // Local-only Ollama modules. ollama.js/ollama-models.js are no longer
  // listed here individually — Phase 8B Step 3 physically relocated both
  // to local/core/, so EXCLUDE_DIRS's own 'local' entry now excludes them
  // by directory, the same as the ONNX runtime files before them (Phase
  // 8B Step 2).
  //
  // core/generation/ollama-provider.js is NOT in this list — it is kept.
  // generation/registry.js's BACKENDS map references createOllamaProvider
  // unconditionally (only ever CALLED when backend === 'ollama'), so it
  // must be a real staged file, not excluded. It is safe to keep because
  // (code review, round 4) it no longer imports core/ollama-lazy.js/
  // local/core/ollama.js at all — its own five *Fn options default to
  // typed-unavailable stubs; the REAL ollama-lazy.js-backed functions are
  // supplied only by admin/bootstrap.js (Full-only, excluded below), via
  // createGenerationRuntime's own createGenerationProviderFn DI seam. Its
  // methods are reachable from Lite only if registry.js's BACKENDS.ollama
  // were actually SELECTED, which Lite's CLI hard pin
  // (SEMIDEX_GENERATION_BACKEND=gemini) prevents regardless.
  //
  // local/admin/system/ollama.js (previously listed here as
  // admin/system/ollama.js) is no longer listed individually — Phase 8B
  // Step 7C physically relocated it to local/admin/, so EXCLUDE_DIRS's own
  // 'local' entry now excludes it by directory, the same as the ONNX/
  // Ollama core runtime files before it (Phase 8B Steps 2-3).
  // core/ollama-lazy.js, core/onnx-embed-lazy.js, and
  // indexer/phases/tag-onnx-lazy.js (code review, round 4 — previously
  // STAGED and CONTENT-substituted with their *.lite.js shims via
  // substituteLazyShims(); that mechanism has been removed entirely). No
  // kept file imports any of the three anymore: core/embeddings.js,
  // indexer/run.js, the phase modules (context.js/tag.js/combined.js/
  // skeleton-summary.js), indexer/preflight.js, and
  // core/generation/ollama-provider.js were all migrated off their own
  // module-scope real-module defaults to explicit capability injection
  // (null until a composition root calls applyXCapability()) — the ONLY
  // remaining importers are indexer/index-full.js, admin/server-full.js,
  // admin/bootstrap.js, and mcp/server.js, all Full-only/excluded below.
  // The three *-lazy.lite.js shim files themselves are also excluded —
  // nothing imports them anymore either (see the LAZY_SHIM_SUBSTITUTIONS
  // removal in lazy-shim-substitutions.mjs's own header comment).
  'core/ollama-lazy.js',
  'core/ollama-lazy.lite.js',
  'core/onnx-embed-lazy.js',
  'core/onnx-embed-lazy.lite.js',
  'indexer/phases/tag-onnx-lazy.js',
  'indexer/phases/tag-onnx-lazy.lite.js',
  // Full-only admin composition pieces — Lite never registers these routes.
  // local/admin/api/onnx.js and local/admin/api/ollama-models.js
  // (previously listed here as admin/api/onnx.js and
  // admin/api/ollama-models.js) are no longer listed individually — Phase
  // 8B Step 7C physically relocated both to local/admin/api/, so
  // EXCLUDE_DIRS's own 'local' entry now excludes them by directory.
  //
  // admin/server-full.js contains createApp() (the FULL composition root)
  // and its Ollama/ONNX-only static imports (now into local/admin/ and
  // shared/admin/ — Phase 8B Step 7C) — split out of admin/server.js
  // specifically so Lite can stage the files it actually needs
  // (registerNeutralRoutes()/createHttpServer() in
  // shared/admin/register-neutral-routes.js; createLiteApp() in
  // admin/composition/lite.js; resolveHostConfig()/resolvePortConfig() in
  // shared/admin/server.js — Phases 3/4, relocated under shared/admin/ in
  // Phase 8B Step 7C) without also staging this file. See
  // server-full.js's own header comment.
  'admin/server-full.js',
  // Full-Semidex-only entry points/composition roots — Lite has its own
  // equivalents (packages/lite/lite-src/serve-lite.js uses
  // createLiteApp()/registerNeutralRoutes() from the STILL-staged
  // admin/composition/lite.js and shared/admin/register-neutral-routes.js
  // (relocated under shared/admin/ in Phase 8B Step 7C), but never imports
  // admin/bootstrap.js itself;
  // packages/lite/lite-src/doctor-lite.js/index-lite.js replace doctor.js/
  // the CLI indexer wrapper; backfill-tags.js/backfill-entity-refs.js/
  // sync.js/smoke.js/bootstrap-docs.js are full-Semidex dev/maintenance
  // tooling with no Lite equivalent).
  'admin/bootstrap.js',
  'doctor.js',
  'backfill-tags.js',
  'backfill-entity-refs.js',
  'sync.js',
  'smoke.js',
  'bootstrap-docs.js',
  // indexer/index.js (the backward-compatible launcher) and
  // indexer/index-full.js (Full's own real capability-injecting entry
  // point) — code review, round 4. indexer/index-lite.js is Lite's own
  // real spawn target and is NOT excluded; it never imports any
  // local-runtime module. indexer/index-runtime.js (the shared
  // CLI/indexing flow both index-full.js and index-lite.js call into) is
  // also NOT excluded — it takes a capability bundle as a parameter and
  // never branches on edition itself.
  'indexer/index.js',
  'indexer/index-full.js',
  // admin/jobs/spawn-indexer-full.js: the ONE file containing both the
  // literal path to indexer/index-full.js AND the node:child_process
  // spawn() call that launches it (code review, round 4) — see that
  // file's own header comment. admin/jobs/registry.js (staged, shared)
  // requires a caller-supplied spawnIndexer with no default of its own, so
  // nothing Lite-reachable imports this file; admin/jobs/spawn-indexer-
  // lite.js is Lite's own sibling and is NOT excluded.
  'admin/jobs/spawn-indexer-full.js',
];
const EXCLUDE_FILE_SET = new Set(EXCLUDE_FILES);

function shouldExcludeDir(relDir) {
  const normalized = relDir.replace(/\\/g, '/');
  return EXCLUDE_DIRS.some((d) => normalized === d || normalized.startsWith(`${d}/`));
}

function shouldExcludeFile(relFile) {
  const normalized = relFile.replace(/\\/g, '/');
  return EXCLUDE_FILE_SET.has(normalized);
}

// ── Step 1: stage src/ ───────────────────────────────────────────────────────

function listAllFiles(dir, base = dir) {
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const rel = relative(base, full);
    const st = statSync(full);
    if (st.isDirectory()) {
      if (shouldExcludeDir(relative(base, full))) continue;
      out.push(...listAllFiles(full, base));
    } else {
      out.push(rel);
    }
  }
  return out;
}

function stageSrc() {
  rmSync(STAGED_SRC, { recursive: true, force: true });
  mkdirSync(STAGED_SRC, { recursive: true });
  const allFiles = listAllFiles(REPO_SRC);
  const staged = [];
  for (const rel of allFiles) {
    if (extname(rel) === '.js' && shouldExcludeFile(rel)) continue;
    const src = join(REPO_SRC, rel);
    const dest = join(STAGED_SRC, rel);
    mkdirSync(dirname(dest), { recursive: true });
    copyFileSync(src, dest);
    staged.push(rel.replace(/\\/g, '/'));
  }
  return staged;
}

// ── Step 2: copy the prebuilt Lite admin UI ─────────────────────────────────

function stageDist({
  source = join(LITE_DIR, '..', '..', 'dist', 'admin-ui-lite'),
  destination = STAGED_DIST,
} = {}) {
  rmSync(destination, { recursive: true, force: true });
  if (!existsSync(source)) {
    throw new Error(`[build] ${relative(REPO_ROOT, source)} does not exist. Run \`npm run admin:build:lite\` before packaging Semidex Lite.`);
  }
  mkdirSync(join(destination, 'admin-ui'), { recursive: true });
  copyDirRecursive(source, join(destination, 'admin-ui'));
}

function copyDirRecursive(src, dest) {
  mkdirSync(dest, { recursive: true });
  for (const entry of readdirSync(src)) {
    const s = join(src, entry);
    const d = join(dest, entry);
    if (statSync(s).isDirectory()) copyDirRecursive(s, d);
    else copyFileSync(s, d);
  }
}

// ── AST parsing helpers ──────────────────────────────────────────────────────

function parseFile(absPath) {
  const src = readFileSync(absPath, 'utf-8');
  return parse(src, { sourceType: 'module', ecmaVersion: 'latest', allowImportExportEverywhere: true });
}

// Resolves a relative or absolute-in-package specifier against `fromFile`
// (a path relative to `root`) to a path relative to `root`, trying the
// extensionless/.js/index.js resolution Node's ESM loader itself uses.
// `root` defaults to STAGED_SRC (the real, single production behavior —
// every call site in this file's own main()/runValidator() flow omits it
// and gets exactly the prior, unparameterized behavior). The optional
// parameter exists ONLY so tests can point this same, real resolution
// logic at an isolated temporary directory instead of mutating the
// shared, generated packages/lite/src/ tree in place — code review
// correctly flagged that a test which renames/creates files inside the
// real staged tree can corrupt it for other test files running in the
// same process, or leave it damaged if the process is killed mid-test.
// This is a minimal, additive signature change (a defaulted parameter,
// not a new code path) — not the broader Full/Lite refactor this task's
// own scope excludes.
function resolveRelativeSpecifier(specifier, fromFileRel, root = STAGED_SRC) {
  if (!specifier.startsWith('.')) return null; // not a relative import
  const fromDir = dirname(join(root, fromFileRel));
  let candidate = resolve(fromDir, specifier);
  const tryPaths = [candidate, `${candidate}.js`, join(candidate, 'index.js')];
  for (const p of tryPaths) {
    if (existsSync(p) && statSync(p).isFile()) return relative(root, p).replace(/\\/g, '/');
  }
  return null; // did not resolve to any staged file
}

/**
 * Extracts every static import/export-from specifier, every literal dynamic
 * import() specifier, every require()/createRequire()-bound-require()
 * literal specifier, and every literal fork()/spawn() first argument (plus
 * `new URL(literal, import.meta.url)` expressions assigned to a const that
 * later flows into fork()/spawn() — the pattern admin/jobs/registry.js and
 * core/ce-rerank.js/tag-onnx.js all use for their child-process entry path).
 */
// Function-like node types acorn produces — used to find the nearest
// enclosing function for a given AST node via its ancestor chain
// (walk.ancestor's own third callback argument). Anything that isn't one
// of these (Program, BlockStatement, etc.) is not a scope boundary this
// validator needs to reason about — parameters are only ever declared on
// a function node.
const FUNCTION_NODE_TYPES = new Set(['FunctionDeclaration', 'FunctionExpression', 'ArrowFunctionExpression']);

function nearestEnclosingFunction(ancestors) {
  for (let i = ancestors.length - 2; i >= 0; i -= 1) {
    if (FUNCTION_NODE_TYPES.has(ancestors[i].type)) return ancestors[i];
  }
  return null; // module/file scope — no enclosing function
}

// Collects EVERY identifier name a function's own parameter list binds —
// plain identifiers (`function f(x)`), default values (`function f(x = 1)`),
// destructured object/array patterns (`function f({ a, b: c }, [d, ...e])`),
// and rest parameters — recursively, regardless of whether that name has
// anything to do with child_process. This is what makes ordinary parameter
// SHADOWING (no default value at all, e.g. `function inner(spawnFn) {...}`)
// detectable: a name can shadow an outer child_process binding by merely
// appearing as ANY kind of parameter of an intervening function, not only
// as the left side of a child_process-sourced AssignmentPattern. Code
// review finding: the previous design only recorded names that were
// themselves bound to a traced child_process import/alias, so a plain
// (non-default) same-named parameter on an intervening function was
// invisible to the outward lookup and incorrectly "saw through" to an
// outer function's real binding.
function collectParamNames(paramNode, out) {
  if (!paramNode) return;
  switch (paramNode.type) {
    case 'Identifier':
      out.add(paramNode.name);
      break;
    case 'AssignmentPattern':
      collectParamNames(paramNode.left, out);
      break;
    case 'ObjectPattern':
      for (const prop of paramNode.properties) {
        if (prop.type === 'RestElement') collectParamNames(prop.argument, out);
        else collectParamNames(prop.value, out);
      }
      break;
    case 'ArrayPattern':
      for (const el of paramNode.elements) collectParamNames(el, out);
      break;
    case 'RestElement':
      collectParamNames(paramNode.argument, out);
      break;
    default:
      break; // other patterns (e.g. computed member expressions) never appear in a param list
  }
}

function collectFunctionParamNames(functionNode) {
  const names = new Set();
  for (const param of functionNode.params) collectParamNames(param, names);
  return names;
}

function extractReferences(ast) {
  const staticImports = [];
  const dynamicImports = []; // { specifier, literal: bool }
  const requireCalls = [];
  const forkSpawnCalls = []; // { callee: 'fork'|'spawn', arg, literal: bool }
  const urlPathConsts = new Map(); // identifier name -> literal path string

  // Module-level (file-scope) identifiers bound to node:child_process's
  // fork/spawn via a real ImportDeclaration (possibly renamed on import,
  // e.g. `import { spawn as nodeSpawn }`) and to Node's require via
  // createRequire(import.meta.url). This IS genuinely file-scoped — an
  // ES module import binding is visible everywhere in the module by
  // construction, so no lexical-scoping concern applies to this map.
  const childProcessImportNames = new Set(); // local name -> 'fork' | 'spawn'
  const childProcessLocalToReal = new Map();
  const requireLocalNames = new Set();

  walkSimple(ast, {
    ImportDeclaration(node) {
      staticImports.push(node.source.value);
      if (node.source.value === 'node:child_process' || node.source.value === 'child_process') {
        for (const spec of node.specifiers) {
          if (spec.type === 'ImportSpecifier' && (spec.imported.name === 'fork' || spec.imported.name === 'spawn')) {
            childProcessImportNames.add(spec.local.name);
            childProcessLocalToReal.set(spec.local.name, spec.imported.name);
          }
        }
      }
    },
    ExportNamedDeclaration(node) {
      if (node.source) staticImports.push(node.source.value);
    },
    ExportAllDeclaration(node) {
      staticImports.push(node.source.value);
    },
    ImportExpression(node) {
      if (node.source.type === 'Literal') {
        dynamicImports.push({ specifier: node.source.value, literal: true });
      } else {
        dynamicImports.push({ specifier: null, literal: false });
      }
    },
    VariableDeclarator(node) {
      // const require = createRequire(import.meta.url);
      if (
        node.init?.type === 'CallExpression'
        && node.init.callee.type === 'Identifier'
        && node.init.callee.name === 'createRequire'
        && node.id.type === 'Identifier'
      ) {
        requireLocalNames.add(node.id.name);
      }
      // const WORKER_PATH = join(__dirname, '../workers/x.js') or
      // fileURLToPath(new URL('../x.js', import.meta.url)) — capture the
      // literal relative path argument for later fork()/spawn() tracing.
      if (node.id.type === 'Identifier') {
        const literalPath = findLiteralRelativePathArg(node.init);
        if (literalPath) urlPathConsts.set(node.id.name, literalPath);
      }
    },
  });

  // Default-parameter binding to a tracked fork/spawn import — e.g.
  // `function f({ spawnFn = nodeSpawn } = {}) { ... spawnFn(...) }`
  // (admin/jobs/registry.js's createJobRegistry() real shape). A SEPARATE
  // walk.ancestor() pass (not part of the walkSimple() pass above)
  // because resolving this correctly needs each AssignmentPattern's and
  // each CallExpression's ANCESTOR CHAIN — which function, if any, each
  // one lexically belongs to — not just the node itself.
  //
  // Design: functionParamBindings maps each FUNCTION NODE to its own
  // local Map(paramName -> realName), populated only from
  // AssignmentPatterns that are DIRECT parameters of that exact function
  // (found via nearestEnclosingFunction() on the AssignmentPattern's own
  // ancestor chain, EXCLUDING the AssignmentPattern itself — a parameter
  // default belongs to the function it parameterizes, not to whatever
  // function might lexically contain an expression inside the default
  // value).
  //
  // resolveChildProcessBinding(name, ancestors) is the ONE shared lookup
  // both the AssignmentPattern pass (resolving node.right) and the
  // CallExpression pass (resolving the callee) use — code review found a
  // second real gap after the first shadowing fix: BOTH passes still
  // checked the file-scope `childProcessImportNames`/`childProcessLocalToReal`
  // maps FIRST, unconditionally, before ever looking at the enclosing
  // function chain — so a DIRECT import shadow (no alias, no default
  // parameter at all — e.g. `import { spawn } from 'node:child_process';
  // function run(spawn) { spawn('./callback.js'); }`) was still
  // misclassified, because `childProcessImportNames.has('spawn')` is true
  // regardless of the fact that THIS particular `spawn` identifier
  // resolves to a local parameter, not the import. Correct real JS lexical
  // resolution order, now followed exactly: walk from the INNERMOST
  // enclosing function outward; at each function, if its OWN parameter
  // list declares this name AT ALL (collectFunctionParamNames — plain
  // parameter, destructured, rest, with or without a default), that is
  // the nearest binding for this name, full stop — check ONLY that
  // function's own functionParamBindings entry (a traced default resolving
  // to a real child_process import) and return its result either way,
  // never continuing outward past it. Only once every enclosing function
  // has been checked and NONE of them declares the name as a parameter at
  // all does the file-scope module import binding apply.
  const functionParamBindings = new Map(); // function node -> Map(paramName -> realName)

  function resolveChildProcessBinding(name, ancestors) {
    for (let i = ancestors.length - 1; i >= 0; i -= 1) {
      const candidate = ancestors[i];
      if (!FUNCTION_NODE_TYPES.has(candidate.type)) continue;
      if (collectFunctionParamNames(candidate).has(name)) {
        // The nearest enclosing function that declares this name AT ALL —
        // this IS the binding for `name`, whatever it resolves to (or
        // doesn't). Never fall through past this point, even if it isn't
        // a traced child_process binding: that would incorrectly "see
        // through" a real local shadow to an outer/module binding.
        return functionParamBindings.get(candidate)?.get(name) ?? null;
      }
    }
    // No enclosing function declares this name as a parameter at all —
    // only now does the file-scope import binding apply.
    return childProcessImportNames.has(name) ? childProcessLocalToReal.get(name) : null;
  }

  walkAncestor(ast, {
    AssignmentPattern(node, _state, ancestors) {
      if (
        node.left?.type !== 'Identifier'
        || node.right?.type !== 'Identifier'
      ) {
        return;
      }
      // ancestors includes `node` itself as the last entry; the function
      // this default parameter belongs to is the nearest FUNCTION ancestor
      // of the AssignmentPattern's OWN position in the tree (a parameter
      // list is a direct child of its function node, so this correctly
      // finds that exact function, never an outer one). node.right's own
      // resolution starts searching from ONE LEVEL OUT (ancestors minus
      // the owning function itself), since a parameter's default value
      // expression is evaluated in the scope OUTSIDE that parameter's own
      // declaration — `function f(spawnFn = spawnFn)` cannot refer to
      // itself.
      const owningFunction = nearestEnclosingFunction(ancestors);
      if (!owningFunction) return; // a top-level default (not inside any function) — cannot be a per-call binding
      const outerAncestors = ancestors.slice(0, ancestors.length - 2); // drop the AssignmentPattern itself AND its owning function
      const realName = resolveChildProcessBinding(node.right.name, outerAncestors);
      if (!realName) return;
      if (!functionParamBindings.has(owningFunction)) functionParamBindings.set(owningFunction, new Map());
      functionParamBindings.get(owningFunction).set(node.left.name, realName);
    },
  });

  walkAncestor(ast, {
    CallExpression(node, _state, ancestors) {
      const callee = node.callee;
      // require('literal') or requireLocalVar('literal')
      if (
        (callee.type === 'Identifier' && (callee.name === 'require' || requireLocalNames.has(callee.name)))
        && node.arguments[0]?.type === 'Literal'
      ) {
        requireCalls.push(node.arguments[0].value);
      }
      if (callee.type !== 'Identifier') return;
      const real = resolveChildProcessBinding(callee.name, ancestors);
      if (!real) return;
      const arg = node.arguments[0];
      // spawn(process.execPath, [ENTRY, ...], opts) — Node's own
      // "re-spawn the current Node binary with an explicit entry-file
      // second argument" pattern (admin/jobs/registry.js's real shape).
      // Distinct from fork(modulePath, args, opts): here the REAL
      // target is arguments[1][0], not arguments[0].
      const isProcessExecPath = arg?.type === 'MemberExpression'
        && arg.object?.type === 'Identifier' && arg.object.name === 'process'
        && arg.property?.type === 'Identifier' && arg.property.name === 'execPath';
      if (isProcessExecPath && node.arguments[1]?.type === 'ArrayExpression') {
        const entryArg = node.arguments[1].elements[0];
        if (entryArg?.type === 'Literal') {
          forkSpawnCalls.push({ callee: real, arg: entryArg.value, literal: true });
        } else if (entryArg?.type === 'Identifier' && urlPathConsts.has(entryArg.name)) {
          forkSpawnCalls.push({ callee: real, arg: urlPathConsts.get(entryArg.name), literal: true });
        } else if (entryArg?.type === 'Identifier') {
          forkSpawnCalls.push({ callee: real, arg: entryArg.name, literal: false });
        } else {
          forkSpawnCalls.push({ callee: real, arg: null, literal: false });
        }
      } else if (arg?.type === 'Literal') {
        forkSpawnCalls.push({ callee: real, arg: arg.value, literal: true });
      } else if (arg?.type === 'Identifier' && urlPathConsts.has(arg.name)) {
        forkSpawnCalls.push({ callee: real, arg: urlPathConsts.get(arg.name), literal: true });
      } else if (arg?.type === 'Identifier') {
        // Not traced to a literal path — could be another dynamic value.
        forkSpawnCalls.push({ callee: real, arg: arg.name, literal: false });
      } else {
        forkSpawnCalls.push({ callee: real, arg: null, literal: false });
      }
    },
  });

  return { staticImports, dynamicImports, requireCalls, forkSpawnCalls };
}

// Recognizes fileURLToPath(new URL('literal', import.meta.url)) and
// join(__dirname, 'literal') shapes, returning the literal relative-path
// argument if found, else null. Does not attempt to resolve __dirname's own
// value — callers only need the literal fragment to check it resolves to a
// staged file relative to the file currently being parsed.
function findLiteralRelativePathArg(node) {
  if (!node || node.type !== 'CallExpression') return null;
  // fileURLToPath(new URL('...', import.meta.url))
  if (node.callee.type === 'Identifier' && node.callee.name === 'fileURLToPath') {
    const inner = node.arguments[0];
    if (inner?.type === 'NewExpression' && inner.callee.name === 'URL' && inner.arguments[0]?.type === 'Literal') {
      return inner.arguments[0].value;
    }
  }
  // join(__dirname, '...') or join(someDir, '...literal...')
  if (node.callee.type === 'Identifier' && node.callee.name === 'join') {
    // The last string-literal argument is the target. Two shapes: a path
    // fragment containing '/' (e.g. '../workers/x.js', already relative-
    // looking) is returned as-is; a bare filename with NO '/' at all
    // (e.g. 'ce-rerank-worker.js' — a same-directory sibling,
    // core/ce-rerank.js's own real shape: `join(__dirname, 'ce-rerank-worker.js')`)
    // is prefixed with './' so resolveRelativeSpecifier() treats it as
    // relative to the CALLING file's own directory, matching what
    // join(__dirname, ...) actually resolves to at runtime. Previously
    // the bare-filename case was silently rejected (the '/' .includes()
    // check required a slash a bare sibling filename never has), which
    // left core/ce-rerank.js's own fork(WORKER_PATH, ...) target
    // unresolved (arg: 'WORKER_PATH', literal: false) rather than
    // correctly resolved to core/ce-rerank-worker.js — found by
    // scripts/audit/build-import-graph.mjs's independent re-implementation
    // of this same extraction.
    const litArgs = node.arguments.filter((a) => a.type === 'Literal' && typeof a.value === 'string');
    const lastLit = litArgs[litArgs.length - 1];
    if (lastLit) {
      return lastLit.value.includes('/') ? lastLit.value : `./${lastLit.value}`;
    }
  }
  return null;
}

// ── Step 3: the five-part closure validator ─────────────────────────────────

// `root` defaults to STAGED_SRC — every real call site (main(), below)
// omits it and gets exactly the prior, unparameterized behavior. The
// optional parameter exists so tests can validate an isolated, temporary
// fixture tree with this SAME real validator logic, instead of writing
// into (and risking corrupting) the shared, generated packages/lite/src/
// staging directory — see resolveRelativeSpecifier()'s own comment for
// the full rationale (code review finding).
function runValidator(stagedFiles, root = STAGED_SRC) {
  const errors = [];
  const pkg = JSON.parse(readFileSync(join(LITE_DIR, 'package.json'), 'utf-8'));
  const declaredDeps = new Set(Object.keys(pkg.dependencies ?? {}));
  const jsFiles = stagedFiles.filter((f) => f.endsWith('.js'));

  for (const relFile of jsFiles) {
    const absPath = join(root, relFile);
    let ast;
    try {
      ast = parseFile(absPath);
    } catch (err) {
      errors.push(`[parse] ${relFile}: ${err.message}`);
      continue;
    }
    const refs = extractReferences(ast);
    const fromDir = dirname(relFile);

    // Check 1: static imports/export-from must resolve to a staged file OR
    // a bare specifier declared in dependencies (checked together with #4).
    for (const specifier of refs.staticImports) {
      checkSpecifier(specifier, relFile, 'static import', errors, declaredDeps);
    }

    // Check 2: literal dynamic imports must resolve to a staged file or a
    // declared dependency. Non-literal dynamic imports cannot be statically
    // verified — flagged as a WARNING via a distinct error prefix so the
    // build surfaces them for manual review rather than silently trusting
    // them (the plan requires no unverifiable escape hatch, but a
    // non-literal import() with no further specifier information genuinely
    // cannot be resolved by any static tool — this is reported, not
    // silently passed).
    for (const dyn of refs.dynamicImports) {
      if (!dyn.literal) {
        errors.push(`[dynamic-import:non-literal] ${relFile}: import() with a non-literal specifier cannot be statically verified — replace with a literal or a fully enumerated map.`);
        continue;
      }
      checkSpecifier(dyn.specifier, relFile, 'dynamic import', errors, declaredDeps);
    }

    // require()/createRequire()-bound require() literal specifiers — same
    // resolution rule as static imports.
    for (const specifier of refs.requireCalls) {
      checkSpecifier(specifier, relFile, 'require()', errors, declaredDeps);
    }

    // Check 3: fork()/spawn() literal path arguments must resolve to a
    // staged file — UNLESS the call is semantically not a local-file
    // dependency at all. No "intentionally absent and unreachable"
    // allow-list for REPO-RELATIVE targets — if a fork/spawn target that
    // was SUPPOSED to be a project file isn't staged, this is an error,
    // full stop. A non-literal fork/spawn argument named exactly `process`
    // combined with `.execPath` (i.e. spawning the current Node binary
    // itself, with the real entry file passed as an explicit second array
    // argument that is ITSELF then checked) is the one recognized safe
    // pattern (admin/jobs/registry.js's own
    // `spawnFn(process.execPath, [INDEXER_ENTRY, path], ...)`) —
    // INDEXER_ENTRY was already resolved via findLiteralRelativePathArg
    // and IS checked here as a literal.
    //
    // isBareOsCommand(call) below replaces an earlier, REJECTED design
    // (a hardcoded TRUSTED_OS_SPAWN_TARGETS Set of specific command
    // names, e.g. 'powershell.exe') — code review correctly identified
    // that as exactly the kind of hardcoded allow-list this validator's
    // own design principle forbids, AND unnecessary: Node's own
    // child_process semantics already distinguish the two cases without
    // naming anything. `spawn(command, args)` resolves `command` through
    // the OS's PATH search unless it contains a path separator (POSIX:
    // any '/'; Windows: '/' or '\\') or starts with '.' — see Node's own
    // child_process docs on `options.shell`/PATH resolution. `fork()`, in
    // contrast, ALWAYS launches a Node module by path — there is no
    // "bare command on PATH" mode for fork() at all, so it is NEVER
    // exempted here, regardless of shape. This is a semantic
    // classification of the CALL SHAPE (does this literal look like a
    // file path at all), not a lookup against any specific program name —
    // 'powershell.exe' needs no more special-casing than 'bash' or
    // 'ffmpeg' would; none of them are ever compared to a name.
    for (const call of refs.forkSpawnCalls) {
      if (call.callee === 'spawn' && call.literal && isBareOsCommand(call.arg)) {
        continue;
      }
      if (!call.literal) {
        errors.push(`[${call.callee}:non-literal] ${relFile}: ${call.callee}() first argument could not be statically resolved to a literal path — no absent-fork-path exception exists; either make the target resolvable or gate/remove this call for Lite.`);
        continue;
      }
      const resolved = resolveRelativeSpecifier(call.arg, relFile, root);
      if (!resolved) {
        errors.push(`[${call.callee}:missing-target] ${relFile}: ${call.callee}('${call.arg}') does not resolve to any staged file.`);
      }
    }
  }

  return errors;

  function checkSpecifier(specifier, relFile, kind, errorsOut, deps) {
    if (specifier.startsWith('.')) {
      const resolved = resolveRelativeSpecifier(specifier, relFile, root);
      if (!resolved) {
        errorsOut.push(`[${kind}:missing-target] ${relFile}: "${specifier}" does not resolve to any staged file.`);
      }
      return;
    }
    if (specifier.startsWith('node:') || NODE_BUILTINS.has(specifier)) return; // Node builtin — always fine
    // Bare package specifier — Check 4: must be declared in dependencies.
    const pkgName = specifier.startsWith('@')
      ? specifier.split('/').slice(0, 2).join('/')
      : specifier.split('/')[0];
    if (!deps.has(pkgName)) {
      errorsOut.push(`[bare-specifier:undeclared] ${relFile}: imports "${specifier}" (package "${pkgName}") which is not in packages/lite/package.json's dependencies.`);
    }
  }
}

const NODE_BUILTINS = new Set([
  'fs', 'path', 'url', 'crypto', 'child_process', 'module', 'util', 'os', 'http', 'https', 'stream', 'events', 'zlib', 'buffer',
]);

// Semantic classification of a literal spawn() first argument as "an OS
// command resolved via PATH search," never a lookup against a specific
// program name (see Check 3's own comment for why a name-based allow-list
// was rejected). Mirrors the shape Node's own child_process module uses
// to decide whether to search PATH: a string containing a path separator
// ('/' on POSIX, '/' or '\\' on Windows) or starting with '.' is treated
// as an explicit path, never searched on PATH — anything else is a bare
// command name. admin/system/folder-picker.js's `spawn('powershell.exe', ...)`
// falls into the bare-command case; this function would classify 'bash',
// './run.sh', '/usr/bin/env', or 'C:\\Windows\\explorer.exe' correctly
// too, without ever having seen any of those literal strings before.
function isBareOsCommand(arg) {
  if (typeof arg !== 'string' || arg.length === 0) return false;
  if (arg.startsWith('.') || arg.includes('/') || arg.includes('\\')) return false;
  return true;
}

// Check 5: staged dist/admin-ui/ must contain no ONNX/Ollama control
// markup/text — a real content scan of the built HTML/JS output (not the
// AST walker above, which only applies to .js source files).
function checkUiAssets(uiDir = join(STAGED_DIST, 'admin-ui')) {
  const errors = [];
  if (!existsSync(uiDir)) {
    return [`[ui-asset:missing] ${relative(LITE_DIR, uiDir)} does not exist.`];
  }
  const indexPath = join(uiDir, 'index.html');
  if (!existsSync(indexPath)) {
    errors.push('[ui-asset:missing] dist/admin-ui/index.html does not exist.');
  }
  const FORBIDDEN_MARKERS = [
    // Local-only setting keys (concrete field names, not shared
    // visibleWhen/dynamicOptions infrastructure).
    'ONNX_EXECUTION_PROVIDER', 'ONNXRUNTIME_NODE_PATH', 'ONNX_MANAGED_RUNTIME', 'OLLAMA_URL', 'GENERATION_DEVICE',
    'ONNX_BATCH_SIZE', 'ONNX_CUDA_STRICT', 'TAG_ONNX_MODEL', 'TAG_ONNX_THREADS', 'TAG_ONNX_ALLOW_DOWNLOAD',
    // Local-only HTML template ids.
    'tpl-gs-onnx-probe-panel',
    // Local-only API route strings — a leaked route string in the JS
    // bundle would mean the Lite UI could still attempt to call a route
    // createLiteApp() never registers (a 404 at runtime, but proof the
    // dead-code path was not actually eliminated).
    '/api/system/onnx-probe', '/api/ollama-models', '/api/system/ollama-status',
    '/api/system/onnx-managed-runtimes',
  ];
  const files = listAllFiles(uiDir).filter((f) => /\.(html|js|css)$/.test(f));
  if (files.length === 0) {
    errors.push('[ui-asset:empty] dist/admin-ui contains no HTML, JavaScript, or CSS assets.');
  }
  if (existsSync(indexPath)) {
    const indexHtml = readFileSync(indexPath, 'utf-8');
    const assetPattern = /(?:src|href)=["']([^"']+)["']/g;
    for (const match of indexHtml.matchAll(assetPattern)) {
      const reference = match[1];
      if (/^(?:[a-z]+:|\/\/|#|data:)/i.test(reference)) continue;
      const assetPath = join(uiDir, reference.replace(/^\//, '').split(/[?#]/, 1)[0]);
      if (!existsSync(assetPath)) {
        errors.push(`[ui-asset:missing-reference] dist/admin-ui/index.html references missing asset "${reference}".`);
      }
    }
  }
  for (const rel of files) {
    const content = readFileSync(join(uiDir, rel), 'utf-8');
    for (const marker of FORBIDDEN_MARKERS) {
      if (content.includes(marker)) {
        errors.push(`[ui-asset:forbidden-marker] dist/admin-ui/${rel}: contains "${marker}" — local-only control leaked into the Lite UI build.`);
      }
    }
  }
  return errors;
}

// ── Main ──────────────────────────────────────────────────────────────────

function main() {
  console.log('[build] staging src/ ...');
  const staged = stageSrc();
  console.log(`[build] staged ${staged.length} files`);

  console.log('[build] staging dist/admin-ui/ ...');
  stageDist();

  console.log('[build] running the five-part closure validator ...');
  const staticErrors = runValidator(listAllFiles(STAGED_SRC).map((f) => f.replace(/\\/g, '/')));
  const uiErrors = checkUiAssets();
  const allErrors = [...staticErrors, ...uiErrors];

  if (allErrors.length > 0) {
    console.error(`\n[build] FAILED — ${allErrors.length} closure violation(s):\n`);
    for (const e of allErrors) console.error(`  ${e}`);
    process.exitCode = 1;
    return;
  }

  console.log(`[build] OK — ${staged.length} files staged, closure validated clean.`);
}

// Only run when executed directly (npm's prepack hook) — importing this
// module for testing (e.g. to call runValidator() against a fixture tree)
// must not have a side effect.
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main();
}

export { extractReferences, parseFile, resolveRelativeSpecifier, runValidator, checkUiAssets, listAllFiles, stageSrc, stageDist };
