// Audit event taxonomy/schema — construction-time contract
// (buildAuditEvent, throws on anything invalid) and the logging-boundary
// non-throwing check (validateAuditEvent). Design record:
// docs/security/audit-logging-design-2026-08.md.
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import {
  AUDIT_EVENT_TYPE, AUDIT_SCHEMA_VERSION, buildAuditEvent, validateAuditEvent, hashIdentifier,
} from '../../../../src/core/audit/event.js';

describe('buildAuditEvent — envelope', () => {
  it('stamps schemaVersion/ts/type and defaults optional envelope fields to null', () => {
    const before = Date.now();
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, { outcome: 'denied' });
    const after = Date.now();
    assert.equal(event.schemaVersion, AUDIT_SCHEMA_VERSION);
    assert.equal(event.type, AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED);
    assert.equal(event.outcome, 'denied');
    assert.ok(Date.parse(event.ts) >= before && Date.parse(event.ts) <= after, 'ts is a real UTC timestamp generated by the builder');
    assert.equal(event.edition, null);
    assert.equal(event.requestId, null);
    assert.equal(event.route, null);
    assert.equal(event.audience, null);
    assert.equal(event.operation, null);
    assert.equal(event.reason, null);
  });

  it('the returned event is frozen', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, { outcome: 'denied' });
    assert.ok(Object.isFrozen(event));
  });

  it('rejects an unknown event type', () => {
    assert.throws(() => buildAuditEvent('not.a.real.type', { outcome: 'denied' }), TypeError);
  });

  it('rejects a missing outcome', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, {}), TypeError);
  });

  it('rejects an outcome outside the fixed vocabulary', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, { outcome: 'whatever' }), TypeError);
  });

  it('rejects a field not allow-listed for the given type', () => {
    assert.throws(
      () => buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, { outcome: 'denied', notARealField: 'x' }),
      /not allow-listed/,
    );
  });

  it('rejects a missing required type-specific field', () => {
    assert.throws(
      () => buildAuditEvent(AUDIT_EVENT_TYPE.AUTHZ_COLLECTION_DENIED, { outcome: 'denied' }),
      /missing required field "collection"/,
    );
  });

  it('rejects a route object with extra keys or wrong shape', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, {
      outcome: 'denied', route: { method: 'GET', path: '/x', extra: 1 },
    }), TypeError);
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, {
      outcome: 'denied', route: { method: 'GET' },
    }), TypeError);
  });

  it('accepts a well-formed route object', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.REQUEST_HOST_REJECTED, {
      outcome: 'denied', route: { method: 'GET', path: '/api/health' },
    });
    assert.deepEqual(event.route, { method: 'GET', path: '/api/health' });
  });
});

describe('buildAuditEvent — newline safety', () => {
  const NEWLINE_FIELDS = [
    ['keyId', AUDIT_EVENT_TYPE.AUTH_INTEGRATION_ACCEPTED, { outcome: 'accepted' }],
    ['keyName', AUDIT_EVENT_TYPE.AUTH_INTEGRATION_ACCEPTED, { outcome: 'accepted', keyId: 'k1' }],
    ['collection', AUDIT_EVENT_TYPE.AUTHZ_COLLECTION_DENIED, { outcome: 'denied' }],
  ];
  for (const [field, type, base] of NEWLINE_FIELDS) {
    it(`rejects a "\\n" embedded in ${field}`, () => {
      assert.throws(() => buildAuditEvent(type, { ...base, [field]: `evil\nvalue` }), TypeError);
    });
    it(`rejects a "\\r" embedded in ${field}`, () => {
      assert.throws(() => buildAuditEvent(type, { ...base, [field]: `evil\rvalue` }), TypeError);
    });
  }

  it('rejects a NUL byte in a string field', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.AUTHZ_COLLECTION_DENIED, {
      outcome: 'denied', collection: 'evil\0value',
    }), TypeError);
  });
});

describe('buildAuditEvent — pathHash', () => {
  it('hashIdentifier() is deterministic, 16 lowercase hex chars, and never contains the input', () => {
    const secretPath = 'C:\\Users\\alice\\Documents\\super-secret-project\\file.md';
    const h1 = hashIdentifier(secretPath);
    const h2 = hashIdentifier(secretPath);
    assert.equal(h1, h2);
    assert.match(h1, /^[0-9a-f]{16}$/);
    assert.doesNotMatch(h1, /alice|secret|Documents/);
  });

  it('two different paths hash to different values (not a constant)', () => {
    assert.notEqual(hashIdentifier('/a/b'), hashIdentifier('/a/c'));
  });

  it('index.root_denied requires a well-formed pathHash, not a raw path', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.INDEX_ROOT_DENIED, {
      outcome: 'denied', pathHash: '/a/raw/path',
    }), TypeError);
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.INDEX_ROOT_DENIED, {
      outcome: 'denied', pathHash: hashIdentifier('/a/raw/path'),
    });
    assert.doesNotMatch(JSON.stringify(event), /\/a\/raw\/path/);
  });
});

describe('buildAuditEvent — admin.settings_changed field allow-list', () => {
  it('accepts UPPER_SNAKE_CASE keys with set/delete actions', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_SETTINGS_CHANGED, {
      outcome: 'changed',
      fields: [{ key: 'QDRANT_URL', action: 'set' }, { key: 'GEMINI_API_KEY', action: 'delete' }],
    });
    assert.deepEqual(event.fields, [{ key: 'QDRANT_URL', action: 'set' }, { key: 'GEMINI_API_KEY', action: 'delete' }]);
  });

  it('rejects a lowercase/mixed-case key', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_SETTINGS_CHANGED, {
      outcome: 'changed', fields: [{ key: 'qdrant_url', action: 'set' }],
    }), TypeError);
  });

  it('rejects an action outside set/delete', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_SETTINGS_CHANGED, {
      outcome: 'changed', fields: [{ key: 'QDRANT_URL', action: 'overwrite' }],
    }), TypeError);
  });

  it('rejects an entry carrying an extra field (e.g. a value)', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_SETTINGS_CHANGED, {
      outcome: 'changed', fields: [{ key: 'QDRANT_URL', action: 'set', value: 'http://evil' }],
    }), TypeError);
  });

  it('rejects an empty fields array', () => {
    assert.throws(() => buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_SETTINGS_CHANGED, {
      outcome: 'changed', fields: [],
    }), TypeError);
  });
});

describe('validateAuditEvent — non-throwing logging-boundary check', () => {
  it('accepts a well-formed event built by buildAuditEvent', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_KEY_CREATED, { outcome: 'created', keyId: 'k1', keyName: 'n' });
    assert.equal(validateAuditEvent(event), true);
  });

  it('never throws for garbage input', () => {
    for (const bad of [null, undefined, 42, 'x', [], {}, { type: 'nope' }]) {
      assert.doesNotThrow(() => validateAuditEvent(bad));
      assert.equal(validateAuditEvent(bad), false);
    }
  });

  it('rejects a wrong schemaVersion', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_KEY_CREATED, { outcome: 'created', keyId: 'k1' });
    assert.equal(validateAuditEvent({ ...event, schemaVersion: 999 }), false);
  });

  it('rejects a tampered/extra field even if the type is otherwise valid', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_KEY_CREATED, { outcome: 'created', keyId: 'k1' });
    assert.equal(validateAuditEvent({ ...event, injected: 'x' }), false);
  });

  it('rejects an event missing a required type-specific field', () => {
    const event = buildAuditEvent(AUDIT_EVENT_TYPE.ADMIN_KEY_CREATED, { outcome: 'created', keyId: 'k1' });
    const { keyId, ...rest } = event;
    assert.equal(validateAuditEvent(rest), false);
  });
});
